// 앱에서 쓰는 아이콘을 전부 도트로 찍는다. 이모지는 기기·폰트마다 모양이 달라서
// 픽셀 캐릭터와 결이 안 맞는다. 그래서 아이콘은 하나도 빠짐없이 여기 손으로 찍어 둔다.
//
// 쓰는 곳:
//  - 하우스 창 (house.js)      : PixelArt.svg(name, px) 로 HTML 안에 바로 넣는다
//  - 펫 스프라이트 (sprite.js) : 장난감 도트를 여기서 가져다 쓴다
//  - 메인 프로세스 (main.js)   : PixelArt.rgba() 로 트레이·우클릭 메뉴 아이콘을 만든다
//
// 도트는 글자 한 칸 = 한 점. '.' 은 투명. 글자 뜻은 아래 PALETTE 에 있다.
// (i18n.js 처럼 렌더러가 <script> 로 읽어야 해서 renderer 폴더에 둔다)
(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.PixelArt = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  const PALETTE = {
    K: '#2b1a10', // 외곽선
    k: '#7a5c3e', // 옅은 선
    W: '#fffaf3', // 흰색
    M: '#efe7da', // 미색
    G: '#d3cabb', // 밝은 회색
    g: '#8a93a3', // 회색
    D: '#4d5563', // 진회색
    R: '#e0574a', // 빨강
    r: '#a8392f', // 진빨강
    O: '#f0913c', // 주황
    o: '#c96a22', // 진주황
    Y: '#ffd35c', // 노랑
    y: '#d99f1e', // 진노랑
    N: '#7cc36a', // 초록
    n: '#4f8f45', // 진초록
    B: '#74b3e8', // 하늘
    b: '#3b6ea5', // 파랑
    P: '#ff8fb0', // 분홍
    p: '#c9557c', // 진분홍
    V: '#b67cff', // 보라
    v: '#7c4fbf', // 진보라
    S: '#f7dcb4', // 살구
    s: '#d9a86b', // 진살구
    C: '#d97757', // 클로드 주황
    c: '#a34f34', // 진한 클로드 주황
    T: '#a97c50', // 나무
    t: '#6b4a2b', // 진나무
    E: '#7d8bff', // 잠(Z) 보라
    e: '#5160c9', // 진한 잠 보라
  };

  // ---------- 아이콘 ----------
  // 대부분 12×12. 장난감만 놀이 화면에서 크게 쓰느라 크기가 제각각이다.
  const ICONS = {
    // ── 탭 ──
    home: [
      '.....KK.....',
      '....KRRK....',
      '...KRRRRK...',
      '..KRRRRRRK..',
      '.KRRRRRRRRK.',
      'KRRRRRRRRRRK',
      'KKKKKKKKKKKK',
      '.KWWWKKWWWK.',
      '.KWWWKKWWWK.',
      '.KWWWKKWWWK.',
      '.KWWWKKWWWK.',
      '.KKKKKKKKKK.',
    ],
    scroll: [
      '............',
      '..KKKKKKKK..',
      '.KttttttttK.',
      '.KSSSSSSSSK.',
      '.KSkkkkkkSK.',
      '.KSSSSSSSSK.',
      '.KSkkkkkSSK.',
      '.KSSSSSSSSK.',
      '.KSkkkkkkSK.',
      '.KSSSSSSSSK.',
      '.KttttttttK.',
      '..KKKKKKKK..',
    ],
    medal: [
      '.KRRK..KBBK.',
      '.KRRK..KBBK.',
      '.KRRK..KBBK.',
      '..KRRKKBBK..',
      '...KKKKKK...',
      '..KYYYYYYK..',
      '.KYYyYYyYYK.',
      'KYYYYyyYYYYK',
      'KYYYYyyYYYYK',
      '.KYYyYYyYYK.',
      '..KYYYYYYK..',
      '...KKKKKK...',
    ],
    ribbon: [
      '............',
      '.KK......KK.',
      'KPPK....KPPK',
      'KPPPK..KPPPK',
      'KPPPPKKPPPPK',
      'KPPPKppKPPPK',
      'KPPPKppKPPPK',
      'KPPPPKKPPPPK',
      'KPPPK..KPPPK',
      'KPPK....KPPK',
      '.KK......KK.',
      '............',
    ],
    coin: [
      '....KKKK....',
      '..KKYYYYKK..',
      '.KYYYYYYYYK.',
      'KYYYyyyyYYYK',
      'KYYyyYYyyYYK',
      'KYYyYYYYYYYK',
      'KYYyYYYYYYYK',
      'KYYyyYYyyYYK',
      'KYYYyyyyYYYK',
      '.KYYYYYYYYK.',
      '..KKYYYYKK..',
      '....KKKK....',
    ],
    chart: [
      '............',
      '.K..........',
      '.K.......RR.',
      '.K.......RR.',
      '.K....YY.RR.',
      '.K....YY.RR.',
      '.K....YY.RR.',
      '.K.NN.YY.RR.',
      '.K.NN.YY.RR.',
      '.KKKKKKKKKK.',
      '............',
      '............',
    ],
    gear: [
      '....KKKK....',
      '.KKKGGGGKKK.',
      '.KGGGGGGGGK.',
      '.KGGGGGGGGK.',
      'KKGGGKKGGGKK',
      'KGGGK..KGGGK',
      'KGGGK..KGGGK',
      'KKGGGKKGGGKK',
      '.KGGGGGGGGK.',
      '.KGGGGGGGGK.',
      '.KKKGGGGKKK.',
      '....KKKK....',
    ],

    // ── 상태·표시 ──
    fire: [
      '.....KK.....',
      '....KRRK....',
      '...KRRRRK...',
      '..KRRRRRRK..',
      '..KRROORRK..',
      '.KRROOOORRK.',
      '.KROOOOOOORK',
      'KROOOYYOOORK',
      'KROOYYYYOORK',
      'KROOOYYOOORK',
      '.KRROOOORRK.',
      '..KKRRRRKK..',
    ],
    plug: [
      '...KK..KK...',
      '...KK..KK...',
      '..KKKKKKKK..',
      '..KggggggK..',
      '..KggggggK..',
      '..KggggggK..',
      '..KggggggK..',
      '..KKKKKKKK..',
      '....DDDD....',
      '.....DD.....',
      '....DD......',
      '...DD.......',
    ],
    pin: [
      '....KKKK....',
      '..KKRRRRKK..',
      '.KRRRRRRRRK.',
      'KRRRWWWWRRRK',
      'KRRWWWWWWRRK',
      'KRRWWWWWWRRK',
      'KRRRWWWWRRRK',
      '.KRRRRRRRRK.',
      '..KRRRRRRK..',
      '...KRRRRK...',
      '....KRRK....',
      '.....KK.....',
    ],
    bell: [
      '.....KK.....',
      '....KYYK....',
      '...KYYYYK...',
      '..KYYYYYYK..',
      '..KYYYYYYK..',
      '.KYYYYYYYYK.',
      '.KYYYYYYYYK.',
      'KYYYYYYYYYYK',
      'KKKKKKKKKKKK',
      '....KYYK....',
      '....KYYK....',
      '.....KK.....',
    ],
    bellOff: [
      '.....KK...R.',
      '....KYYK.R..',
      '...KYYYRK...',
      '..KYYYRYYK..',
      '..KYYRYYYK..',
      '.KYYRYYYYYK.',
      '.KYRYYYYYYK.',
      'KYRYYYYYYYYK',
      'KRKKKKKKKKKK',
      'R...KYYK....',
      '....KYYK....',
      '.....KK.....',
    ],
    eye: [
      '............',
      '............',
      '............',
      '....KKKK....',
      '..KKWWWWKK..',
      '.KWWWKKWWWK.',
      'KWWWKbbKWWWK',
      'KWWWKbbKWWWK',
      '.KWWWKKWWWK.',
      '..KKWWWWKK..',
      '....KKKK....',
      '............',
    ],
    laptop: [
      '............',
      '............',
      '..KKKKKKKK..',
      '..KDDDDDDK..',
      '..KDBBBBDK..',
      '..KDBBBBDK..',
      '..KDDDDDDK..',
      '.KKKKKKKKKK.',
      'KggggggggggK',
      '.KKKKKKKKKK.',
      '............',
      '............',
    ],
    bang: [
      '....KKKK....',
      '....KRRK....',
      '....KRRK....',
      '....KRRK....',
      '....KRRK....',
      '....KRRK....',
      '....KRRK....',
      '....KKKK....',
      '............',
      '....KKKK....',
      '....KRRK....',
      '....KKKK....',
    ],
    zzz: [
      '......EEEE..',
      '.......EE...',
      '......EE....',
      '......EEEE..',
      '............',
      '.EEEEEE.....',
      '....EEE.....',
      '...EEE......',
      '..EEE.......',
      '.EEEEEE.....',
      '............',
      '............',
    ],
    doze: [
      '............',
      '............',
      '......EEEE..',
      '.......EE...',
      '......EE....',
      '......EEEE..',
      '............',
      '...EEEE.....',
      '.....E......',
      '....E.......',
      '...EEEE.....',
      '............',
    ],
    lock: [
      '...KKKKKK...',
      '..KKGGGGKK..',
      '..KGKKKKGK..',
      '..KGK..KGK..',
      '.KKKKKKKKKK.',
      'KYYYYYYYYYYK',
      'KYYYYKKYYYYK',
      'KYYYYKKYYYYK',
      'KYYYYKKYYYYK',
      'KYYYYYYYYYYK',
      '.KKKKKKKKKK.',
      '............',
    ],
    gift: [
      '...K....K...',
      '..KRK..KRK..',
      '...KRKKRK...',
      '.KKKKRRKKKK.',
      '.KYYYKKYYYK.',
      '.KKKKRRKKKK.',
      '.KYYYKKYYYK.',
      '.KYYYKKYYYK.',
      '.KYYYKKYYYK.',
      '.KYYYKKYYYK.',
      '.KKKKKKKKKK.',
      '............',
    ],
    check: [
      '............',
      '............',
      '............',
      '..........K.',
      '.........KNK',
      '.K......KNK.',
      'KNK....KNK..',
      '.KNK..KNK...',
      '..KNKKNK....',
      '...KNNK.....',
      '....KK......',
      '............',
    ],
    bulb: [
      '....KKKK....',
      '..KKYYYYKK..',
      '.KYYYYYYYYK.',
      'KYYYYYYYYYYK',
      'KYYYYYYYYYYK',
      'KYYYYYYYYYYK',
      '.KYYYYYYYYK.',
      '..KYYYYYYK..',
      '..KKKKKKKK..',
      '...KGGGGK...',
      '...KGGGGK...',
      '....KKKK....',
    ],
    hourglass: [
      '.KKKKKKKKKK.',
      '.KYYYYYYYYK.',
      '..KYYYYYYK..',
      '...KYYYYK...',
      '....KYYK....',
      '.....KK.....',
      '.....KK.....',
      '....KYYK....',
      '...KYYYYK...',
      '..KYYYYYYK..',
      '.KYYYYYYYYK.',
      '.KKKKKKKKKK.',
    ],
    star: [
      '.....KK.....',
      '....KYYK....',
      '....KYYK....',
      'KKKKKYYKKKKK',
      'KYYYYYYYYYYK',
      '.KYYYYYYYYK.',
      '..KYYYYYYK..',
      '..KYYYYYYK..',
      '.KYYKKKYYK..',
      'KYYK...KYYK.',
      'KKK.....KKK.',
      '............',
    ],
    sparkle: [
      '.....KK.....',
      '.....KK.....',
      '....KYYK....',
      '....KYYK....',
      'KKKKKYYKKKKK',
      'KYYYYYYYYYYK',
      'KYYYYYYYYYYK',
      'KKKKKYYKKKKK',
      '....KYYK....',
      '....KYYK....',
      '.....KK.....',
      '.....KK.....',
    ],
    // AI 활용 팁 말풍선 앞: 코스튬 효과 'Claude가 생각 중…' 처럼 생각 풍선 속 Claude 주황 반짝이 + 점 둘
    claudethink: [
      '.KKKKKKKKKKK.',
      'KWWWWWWWWWWWK',
      'KWCWCWCWWWWWK',
      'KWWCCCWWWWWWK',
      'KWCCCCCWgWgWK',
      'KWWCCCWWWWWWK',
      'KWCWCWCWWWWWK',
      'KWWWWWWWWWWWK',
      '.KKKKKKKKKKK.',
      '..KK.........',
      '.K...........',
    ],
    stretch: [
      '.....KK.....',
      '....KNNK....',
      '...KNNNNK...',
      '..KNNNNNNK..',
      '....KNNK....',
      '....KNNK....',
      '....KNNK....',
      '....KNNK....',
      '..KNNNNNNK..',
      '...KNNNNK...',
      '....KNNK....',
      '.....KK.....',
    ],
    // 리본 아이콘: 고양이 얼굴 윤곽 (좌우 대칭, 한 색. 옵시디언 아이콘처럼 글자색을 따른다 — main.js pixelIcon mono)
    catface: [
      '.K........K.',
      '.KK......KK.',
      '.K.K....K.K.',
      '.K..KKKK..K.',
      'K..........K',
      'K..K....K..K',
      'K..K....K..K',
      'K....KK....K',
      'K..........K',
      '.K........K.',
      '..KKKKKKKK..',
    ],
    paw: [
      'KKK.KKK.KKK.',
      'KSK.KSK.KSK.',
      'KSK.KSK.KSK.',
      'KKK.KKK.KKK.',
      '............',
      '..KKKKKKKK..',
      '.KSSSSSSSSK.',
      'KSSSSSSSSSSK',
      'KSSSSSSSSSSK',
      '.KSSSSSSSSK.',
      '..KKKKKKKK..',
      '............',
    ],
    wave: [
      'KKK.KKK.KKK.',
      'KSK.KSK.KSK.',
      'KSK.KSK.KSK.',
      'KKK.KKK.KKK.',
      '...........K',
      '..KKKKKK..K.',
      '.KSSSSSSK.K.',
      'KSSSSSSSSKK.',
      'KSSSSSSSSK.K',
      '.KSSSSSSK..K',
      '..KKKKKK....',
      '............',
    ],
    chat: [
      '..KKKKKKKK..',
      '.KWWWWWWWWK.',
      'KWWWWWWWWWWK',
      'KWWWWWWWWWWK',
      'KWKKWKKWKKWK',
      'KWKKWKKWKKWK',
      'KWWWWWWWWWWK',
      'KWWWWWWWWWWK',
      '.KWWWWWWWWK.',
      '..KKKWWKKKK.',
      '....KWWK....',
      '....KKK.....',
    ],
    chats: [
      '.KKKKKKK....',
      'KWWWWWWWK...',
      'KWWWWWWWK...',
      'KWWWWWWWK...',
      'KWWWWWWWK...',
      '.KKWWWKKK...',
      '...KWK.KKKKK',
      '...KK.KWWWWK',
      '......KWWWWK',
      '......KWWWWK',
      '......KKWWKK',
      '........KK..',
    ],
    heart: [
      '............',
      '..KKK..KKK..',
      '.KRRRKKRRRK.',
      'KRRWRRRRRRRK',
      'KRRWRRRRRRRK',
      'KRRRRRRRRRRK',
      '.KRRRRRRRRK.',
      '..KRRRRRRK..',
      '...KRRRRK...',
      '....KRRK....',
      '.....KK.....',
      '............',
    ],
    door: [
      '.KKKKKKKKKK.',
      '.KTTTTTTTTK.',
      '.KTTTTTTTTK.',
      '.KTTTTTTTTK.',
      '.KTTTTTTTTK.',
      '.KTTTTTTYTK.',
      '.KTTTTTTYTK.',
      '.KTTTTTTTTK.',
      '.KTTTTTTTTK.',
      '.KTTTTTTTTK.',
      '.KTTTTTTTTK.',
      '.KKKKKKKKKK.',
    ],
    moneybag: [
      '....KKKK....',
      '....KttK....',
      '...KKttKK...',
      '..KKYYYYKK..',
      '.KYYYYYYYYK.',
      'KYYYYYYYYYYK',
      'KYYYYyyYYYYK',
      'KYYYyWWyYYYK',
      'KYYYYyyYYYYK',
      'KYYYYYYYYYYK',
      '.KYYYYYYYYK.',
      '..KKKKKKKK..',
    ],
    gem: [
      '............',
      '..KKKKKKKK..',
      '.KBBKBBKBBK.',
      'KBBBBBBBBBBK',
      'KBBBBBBBBBBK',
      '.KBBBBBBBBK.',
      '..KBBBBBBK..',
      '...KBBBBK...',
      '....KBBK....',
      '.....KK.....',
      '............',
      '............',
    ],
    calendar: [
      '..KK....KK..',
      'KKKKKKKKKKKK',
      'KRRRRRRRRRRK',
      'KKKKKKKKKKKK',
      'KWWWWWWWWWWK',
      'KWKKWKKWKKWK',
      'KWWWWWWWWWWK',
      'KWKKWKKWKKWK',
      'KWWWWWWWWWWK',
      'KWKKWKKWKKWK',
      'KWWWWWWWWWWK',
      'KKKKKKKKKKKK',
    ],
    trophy: [
      'KKKKKKKKKKKK',
      'KYYYYYYYYYYK',
      'KYYYYYYYYYYK',
      'KKYYYYYYYYKK',
      '.KYYYYYYYYK.',
      '..KYYYYYYK..',
      '...KYYYYK...',
      '....KYYK....',
      '....KYYK....',
      '...KKKKKK...',
      '..KYYYYYYK..',
      '..KKKKKKKK..',
    ],
    moon: [
      '.....KKKK...',
      '...KKYYYYK..',
      '..KYYYYKKK..',
      '.KYYYYK.....',
      '.KYYYK......',
      'KYYYYK......',
      'KYYYYK......',
      '.KYYYK......',
      '.KYYYYK.....',
      '..KYYYYKKK..',
      '...KKYYYYK..',
      '.....KKKK...',
    ],
    sunrise: [
      '............',
      '.....YY.....',
      '.....YY.....',
      'Y...KKKK...Y',
      '.Y.KYYYYK.Y.',
      '..KYYYYYYK..',
      '.KYYYYYYYYK.',
      'KYYYYYYYYYYK',
      'KYYYYYYYYYYK',
      'KKKKKKKKKKKK',
      '............',
      'oooooooooooo',
    ],
    clock: [
      '..K......K..',
      '...KKKKKK...',
      '..KWWWWWWK..',
      '.KWWWWWWWWK.',
      'KWWWWKWWWWWK',
      'KWWWWKWWWWWK',
      'KWWWKKKWWWWK',
      'KWWWWWWWWWWK',
      'KWWWWWWWWWWK',
      '.KWWWWWWWWK.',
      '..KWWWWWWK..',
      '...KKKKKK...',
    ],
    ricebowl: [
      '............',
      '...W..W..W..',
      '..W..W..W...',
      '...KKKKKK...',
      '..KWWWWWWK..',
      '.KWWWWWWWWK.',
      'KKKKKKKKKKKK',
      '.KCCCCCCCCK.',
      '.KCCCCCCCCK.',
      '..KCCCCCCK..',
      '...KKKKKK...',
      '............',
    ],
    pillow: [
      '............',
      '............',
      '..KKKKKKKK..',
      '.KBBBBBBBBK.',
      'KBBBBBBBBBBK',
      'KBBbbbbbbBBK',
      'KBBBBBBBBBBK',
      'KBBBBBBBBBBK',
      '.KBBBBBBBBK.',
      '..KKKKKKKK..',
      '............',
      '............',
    ],
    map: [
      '.KKKKKKKKKK.',
      'KSSSSSSSSSSK',
      'KSSKSSSSSSSK',
      'KSSKSSSSSSSK',
      'KSSKKSSSSSSK',
      'KSSSKSSSSSSK',
      'KSSSKSSKSSSK',
      'KSSSKSSSKSSK',
      'KSSSSSSKSSSK',
      'KSSSSSSSKRSK',
      'KSSSSSSSSSSK',
      '.KKKKKKKKKK.',
    ],
    leaf: [
      '..........K.',
      '.........KK.',
      '.......KKNK.',
      '.....KKNNNK.',
      '...KKNNNNKK.',
      '..KNNNNNKK..',
      '.KNNNNNKK...',
      'KNNNNNKK....',
      'KNNNKK......',
      'KNKKK.......',
      'KK..........',
      '............',
    ],

    // ── 악세사리 ──
    none: [
      '............',
      '............',
      '............',
      '............',
      '............',
      '..GGGGGGGG..',
      '..GGGGGGGG..',
      '............',
      '............',
      '............',
      '............',
      '............',
    ],
    sprout: [
      '............',
      '..KKK..KKK..',
      '.KNNNKKNNNK.',
      '.KNNNKKNNNK.',
      '.KNNNKKNNNK.',
      '..KKKKKKKK..',
      '.....KK.....',
      '.....nn.....',
      '.....nn.....',
      '.....KK.....',
      '............',
      '............',
    ],
    vpEggshell: [
      '............',
      '............',
      '............',
      '.K...K...K..',
      'KWK.KWK.KWK.',
      'KWWKWBWKWWK.',
      'KBWWWWWWMBK.',
      'KWWMWWWMWWK.',
      '.KWWWWWWWK..',
      '..KKKKKKK...',
      '............',
      '............',
    ],
    glasses: [
      '............',
      '............',
      '..KKK..KKK..',
      '.KBBBKKBBBK.',
      'KBBBBKKBBBBK',
      'KBBBBKKBBBBK',
      '.KBBBKKBBBK.',
      '..KKK..KKK..',
      '............',
      '............',
      '............',
      '............',
    ],
    headphones: [
      '...KKKKKK...',
      '..KDDDDDDK..',
      '.KDKKKKKKDK.',
      '.KDK....KDK.',
      'KKDKK..KKDKK',
      'KDDDK..KDDDK',
      'KDCDK..KDCDK',
      'KDCDK..KDCDK',
      'KDDDK..KDDDK',
      'KKKKK..KKKKK',
      '............',
      '............',
    ],
    beanie: [
      '.....KK.....',
      '....KWWK....',
      '.....KK.....',
      '...KKKKKK...',
      '..KBBBBBBK..',
      '.KBBBBBBBBK.',
      'KBBBBBBBBBBK',
      'KKKKKKKKKKKK',
      'KbbbbbbbbbbK',
      'KKKKKKKKKKKK',
      '............',
      '............',
    ],
    scarf: [
      '............',
      '............',
      '.KKKKKKKKKK.',
      'KNNNNNNNNNNK',
      'KNNNNNNNNNNK',
      'KnnnnnnnnnnK',
      'KKKKKKKKKKKK',
      '..KNNK......',
      '..KNNK......',
      '..KNNK......',
      '..KnnK......',
      '..KKKK......',
    ],
    nightcap: [
      '............',
      '.........KK.',
      '........KWK.',
      '.......KEK..',
      '.....KKEK...',
      '...KKEEK....',
      '..KEEEEK....',
      '.KEEEEEEK...',
      'KEEEEEEEEK..',
      'KeeeeeeeeeeK',
      'KKKKKKKKKKKK',
      '............',
    ],
    party: [
      '.....KK.....',
      '....KYYK....',
      '....KVVK....',
      '...KVVVVK...',
      '...KVvvVK...',
      '..KVVVVVVK..',
      '..KVvvvvVK..',
      '.KVVVVVVVVK.',
      '.KVvvvvvvVK.',
      'KVVVVVVVVVVK',
      'KKKKKKKKKKKK',
      '............',
    ],
    chef: [
      '............',
      '..KKKKKKKK..',
      '.KWWWWWWWWK.',
      'KWWWWWWWWWWK',
      'KWWWWWWWWWWK',
      '.KWWWWWWWWK.',
      '..KWWWWWWK..',
      '..KKKKKKKK..',
      '.KWWWWWWWWK.',
      '.KGGGGGGGGK.',
      '.KKKKKKKKKK.',
      '............',
    ],
    crown: [
      '............',
      '............',
      '.K...KK...K.',
      'KYK.KYYK.KYK',
      'KYKKKYYKKKYK',
      'KYYYYYYYYYYK',
      'KYYYRYYRYYYK',
      'KYYYYYYYYYYK',
      'KyyyyyyyyyyK',
      'KKKKKKKKKKKK',
      '............',
      '............',
    ],
    bowtie: [
      '............',
      '............',
      '.KK......KK.',
      'KRRK....KRRK',
      'KRRRKKKKRRRK',
      'KRRRKYYKRRRK',
      'KRRRKYYKRRRK',
      'KRRRKKKKRRRK',
      'KRRK....KRRK',
      '.KK......KK.',
      '............',
      '............',
    ],
    bandana: [
      '............',
      '............',
      '............',
      '.KKKKKKKKKK.',
      'KRRWRRRRWRRK',
      'KRRRRRRRRRRK',
      'KRRRRWRRRRRK',
      '.KRRRRRRRRK.',
      '..KRRRRRRK..',
      '...KRRRRK...',
      '....KRRK....',
      '.....KK.....',
    ],
    halo: [
      '............',
      '............',
      '............',
      '..KKKKKKKK..',
      '.KYYYYYYYYK.',
      'KYYK....KYYK',
      'KYYK....KYYK',
      '.KYYYYYYYYK.',
      '..KKKKKKKK..',
      '............',
      '............',
      '............',
    ],
    santa: [
      '............',
      '.........KK.',
      '........KWK.',
      '.......KRK..',
      '.....KKRK...',
      '...KKRRK....',
      '..KRRRRK....',
      '.KRRRRRRK...',
      'KRRRRRRRRK..',
      'KWWWWWWWWWWK',
      'KKKKKKKKKKKK',
      '............',
    ],

    // ── 간식 ──
  };

  // 먹이 도트는 16×16 에 두 톤 음영을 넣어서 색이 더 많다. 그래서 팔레트를 따로 쓴다
  const FOOD_PALETTE = {
    'K': '#2b1a10', 'W': '#fffaf3', 'w': '#f1e6d2', 'G': '#d3cabb', 'g': '#9aa0aa', 'D': '#565d69',
    'R': '#e5463f', 'r': '#a52e2a', 'P': '#ff9bb8', 'p': '#e0668f', 'Q': '#ffd0dd', 'O': '#f59232',
    'o': '#c8661b', 'A': '#ff9e7a', 'a': '#e0714c', 'Y': '#ffd65a', 'y': '#e0a91e', 'E': '#ffb930',
    'N': '#79c46b', 'n': '#4a8c42', 'B': '#72b3ea', 'b': '#3a6fb0', 'U': '#cfe8f7', 'T': '#e0a764',
    't': '#b07436', 'S': '#f6d7a2', 'C': '#8a5a34', 'c': '#5c3a1f', 'V': '#b683f2', 'v': '#8454c4',
    'M': '#9fe3c8', 'm': '#5cb895', 'H': '#ffffff', 'X': '#2f3a33', 'Z': '#f0535a', 'I': '#fbf7ee',
    's': '#e3b877',
  };

  // 먹이 — 밥 11 + 간식 24. 상점 카드·우클릭 메뉴·바닥에 떨어진 먹이가 모두 이 그림을 쓴다
  const FOOD = {
    // ---------- 3차 (2026-09-22): 기운 음식 4 + 간식 3 ----------
    cookieMilk: [
      '................',
      '................',
      '................',
      '.....KKKK.......',
      '....KCcCCK.KKK..',
      '...KCCCCcCKCcCK.',
      '..KKCcCCCKKCCcK.',
      '.KWCCCcCCWCCCWK.',
      '.KCcWCCCcCCcWCK.',
      'KKKKKKKKKKKKKKKK',
      'KBBBBBBBBBBBBBBK',
      'KBHBBHBBHBBHBBBK',
      '.KBBBBBBBBBBBBK.',
      '..KbbbbbbbbbbK..',
      '...KKKKKKKKKK...',
      '................',
    ],
    dubaiSmelt: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '.......KKKK.....',
      '..KKKKKNnNNKK.KK',
      '.KGHGKNNnNKCCKCK',
      'KGWKGCKNNKCCCCCK',
      'KGGGGCCKKCCCCcK.',
      '.KgGGcCCCCCccKcK',
      '..KKKKKKKKKKK.KK',
      '................',
      '................',
      '................',
      '................',
    ],
    pumpkinLatte: [
      '................',
      '.......KK.......',
      '......KnnK......',
      '....KKKnnKKK....',
      '...KWWHWWHWWK...',
      '..KOoOOoOOoOOK..',
      '.KOOoOOoOOoOOKKK',
      '.KOOoOOoOOoOOK.K',
      '.KOOoOOoOOoOOK.K',
      '.KOOoOOoOOoOOKKK',
      '..KOoOOoOOoOK...',
      '...KKOoOOoKK....',
      '.....KKKKK......',
      '..KKKKKKKKKKK...',
      '................',
      '................',
    ],
    tonkotsu: [
      '................',
      '..........KKK...',
      '.........KXXK...',
      '.........KXXK...',
      '....KKKKKXXK....',
      '..KKDDDDDXXDKK..',
      '.KDTTTWNWWXXWDK.',
      'KDWTtTWWYYWwNWDK',
      'KDWTTtWNYYWWwWDK',
      'KDDwWWWWwWNWwDDK',
      'KXXXXXXXXXXXXXXK',
      '.KXDXRXXRXXRXXK.',
      '.KXDXXXXXXXXXXK.',
      '..KXXXXXXXXXXK..',
      '...KKXXXXXXKK...',
      '....KKKKKKKK....',
    ],
    truffleJjajang: [
      '.......KK.......',
      '......KYYK......',
      '......KYEK......',
      '.......KK.......',
      '................',
      '.....KKKKKK.....',
      '...KKcCcCcCKK...',
      '..KcCTcCwcCcCK..',
      '.KWcCcYcTcCcCWK.',
      '.KWWcWcCcWcWWwK.',
      '.KwWWWWWWWWWWwK.',
      'KWKKKKKKKKKKKKWK',
      'KwWWWWWWWWWWWWwK',
      '.KwwwwwwwwwwwwK.',
      '..KKKKKKKKKKKK..',
      '................',
    ],
    emberChicken: [
      '......G...G.....',
      '.....G...G......',
      '......G...G.....',
      '....KKKKKKKK....',
      '..KKYHYYEYYEKK..',
      '.KEYHYYcEYYYEyK.',
      '.KEYYcYYYEcYyyK.',
      '..KKyEyyEyyyKK..',
      'KDDDDDDDDDDDDDDK',
      '.KDKDKDKDKDKDKK.',
      '.KOYRORYYROROYK.',
      '.KRORrOrRrOrORK.',
      '..KXXXXXXXXXXK..',
      '...KKKKKKKKKK...',
      '................',
      '................',
    ],
    grandmaKimchi: [
      '................',
      '.....K.K.K......',
      '....KNKNKNK.....',
      '....KnNnNnK.....',
      '...KRNRNRnRK....',
      '..KRrRRrRRrRK...',
      '.KRRWRrRRWRrRKK.',
      'KKKKKKKKKKKKKNnK',
      'KCCCCCCCCCCCKKNK',
      'KCTCCCCCCCCcK.nK',
      'KCttttttttttK.KK',
      '.KCCCCCCCCCcK...',
      '..KcCCCCCCccK...',
      '...KKKKKKKKK....',
      '................',
      '................',
    ],
    // ---------- 간식 2차 (2026-09-22): 고양이 세계에만 있는 수상한 간식들 ----------
    // S1 말랑말랑 생쥐 앞다리
    mouseleg: [
      '................',
      '................',
      '................',
      '...........KK...',
      '..........KPPK..',
      '.........KPQPK..',
      '........KGGKK...',
      '.......KGGGK....',
      '......KGGgK.....',
      '.....KGGgK......',
      '....KGGgK.......',
      '...KWWK.........',
      '..KWKWK.........',
      '..KK.KK.........',
      '................',
      '................',
    ],
    // S2 싱싱한 슈크림 붕어빵
    creamtaiyaki: [
      '................',
      '................',
      '................',
      '..B.............',
      '.BU..B..........',
      '..B..U..........',
      '...KKKKKKKKK....',
      '..KTTTtTtTTTKK..',
      '.KTKTtTtTtTKYYK.',
      'KTTTTTTTTTTKYHYK',
      'KTTtTtTtTtTKYYYK',
      '.KtTTTTTTTTTKYK.',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
      '................',
    ],
    // S3 냉동 바퀴벌레 칩
    roachchip: [
      '..............H.',
      '.............HHH',
      '..KKKKKKKKKKKKH.',
      '..KHWUUUUUUUBK..',
      '..KWUKUUUUKUBK..',
      '..KUUUKUUKUUBK..',
      '..KUUUUccUUUBK..',
      '..KUKUCTCCUKBK..',
      '..KUUKCTCCKUBK..',
      '..KUKUCCCcUKBK..',
      '..KUUUCCccUUBK..',
      '..KUUUUccUUUBK..',
      '..KBBBBBBBBBbK..',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
    ],
    // S4 후끈따끈 캣닢 티백
    nipteabag: [
      '................',
      '.......G...G....',
      '......G...G.....',
      '.......G...G....',
      '..KKKKKKKKKKK...',
      '.K.KMMmMMMmMK...',
      '.K.KWHWWWWWWKKK.',
      '.K.KWHWWWWWWK.K.',
      'KKKKWWWWWWWwK.K.',
      'KNnKWWWWWWWwKKK.',
      'KnNKWWWWWWwwK...',
      'KKKKwWWWWWwwK...',
      '...KKwwwwwwKK...',
      '....KKKKKKKK....',
      '................',
      '................',
    ],
    // S5 바삭바삭 귀뚜라미 튀김
    cricket: [
      '..KK............',
      '....KK..........',
      '......K...KKK...',
      '..K....K.KEEEK..',
      '...KKKKKKEYEEK..',
      '..KEEEEKEYEEK...',
      '.KEHEYEEYEEEEK..',
      'KEKEEEYEEEYEyyK.',
      'KEEEyEEEyEEyyyK.',
      '.KyyEEyyEEyyyK.K',
      '..KKKKKKKKKKK.K.',
      '..K.K...K.K..K..',
      '................',
      '................',
      '................',
      '................',
    ],
    // S6 새콤달콤 모기 젤리
    mosquitojelly: [
      '................',
      '................',
      '................',
      '.....KKKKKK.....',
      '...KKQQQQQQKK...',
      '..KQHQQWWQWWPK..',
      '..KQHQQQWDWQPK..',
      '.KQQKQQKDDKQQPK.',
      '.KQQQKKDDQQKQPK.',
      '.KQQKQDKQQQQQPK.',
      '.KQQQKQQQQQQPPK.',
      '.KPQQQQQQQQPPpK.',
      '..KppppppppppK..',
      '.KKKKKKKKKKKKKK.',
      'KWWWWWWWWWWWWWwK',
      '.KKKKKKKKKKKKKK.',
    ],
    // S7 톡 쏘는 파리 사이다
    flysoda: [
      '......KKKK......',
      '......KRrK......',
      '......KKKK......',
      '......KNHK......',
      '......KNNK......',
      '.....KNHNnK.....',
      '....KNHNNNnK....',
      '....KNHNUNnK....',
      '....KWWWWWWK....',
      '....KWUKUWWK....',
      '....KWWKWWWK....',
      '....KWWWWWWK....',
      '....KNNUNNnK....',
      '....KNNNNnnK....',
      '....KKKKKKKK....',
      '................',
    ],
    // S8 개구리알 버블티
    frogtea: [
      '..........KK....',
      '.........KBK....',
      '........KBK.....',
      '....KKKKBKKK....',
      '...KUHUKBKUUK...',
      '..KKKKKKKKKKKK..',
      '..KMMMMMMMMMMK..',
      '..KMHMMMMMMMmK..',
      '...KMMMMMMMmK...',
      '...KUXUMUXUmK...',
      '...KMUMUXUMmK...',
      '....KUXUMUXK....',
      '....KMUMUXmK....',
      '.....KKKKKK.....',
      '................',
      '................',
    ],
    // S9 쫀득쫀득 지렁이 구미
    wormgummy: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '...KKKK.........',
      '..KYHYYK........',
      '.KYHYyYYK.......',
      '.KYYKKyYYK...KK.',
      'KYYK..KYOOK.KQPK',
      'KyYK...KOPPKQPpK',
      '.KK.....KPPPPpK.',
      '.........KKKKK..',
      '................',
      '................',
    ],
    // S10 매콤 도마뱀 꼬리 떡볶이
    lizardtteok: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '.........NN.....',
      '........NnN.....',
      '..KKKKKKKKKKK...',
      '.KWRRRRNRRRRWK..',
      '.KRKNRRRRNKRRK..',
      '.KRRRRNRRRRRRK..',
      '..KWWWWWWWWWK...',
      '...KKKKKKKKK....',
      '................',
      '................',
      '................',
    ],
    // S11 집사 머리카락 솜사탕
    hairfloss: [
      '.......c........',
      '....KK..c.KK....',
      '...KQQKKKKPPK...',
      '..KQHQQPQPPPpK..',
      '.KQQQPQPcPPPPpK.',
      '.KQPQPPcPPPPppK.',
      'KPQQPPcPPPPPPppK',
      '.KPPPPPPPPPPppK.',
      '..KpPPPPPPPppK..',
      '...KKppppppKK...',
      '.....KKTTKK.....',
      '.......KTK......',
      '.......KTK......',
      '.......KtK......',
      '........K.......',
      '................',
    ],
    // S13 녹아내리는 츄르 아이스바
    churubar: [
      '................',
      '................',
      '................',
      '.....KKKKK......',
      '....KOOOOOK.....',
      '....KOHOOoK.....',
      '....KOHOOoK.....',
      '....KOOOOoK.....',
      '....KOOOOoK.....',
      '....KOKOOoKK....',
      '....KKOKOKOK....',
      '......KTKKOK....',
      '......KTK.K.....',
      '......KtK...O...',
      '.......K........',
      '................',
    ],
    // S15 새벽 3시 참치 라떼
    tunalatte: [
      '...........KKK..',
      '..........KYYK..',
      '..........KYK...',
      '..........KYYK..',
      '...KKKKKKKKKKK..',
      '..KWTTTTTTWK....',
      '.KWTWTWWWTTWK...',
      '.KWTWWWWKWTWKKK.',
      '.KWTWTWWWTTWK.K.',
      '.KWWTTTTTTWWK.K.',
      '.KWWWWWWWWWwKKK.',
      '.KHWWWWWWWWwK...',
      '..KWWWWWWWwK....',
      'KKKKKKKKKKKKKKK.',
      '.KGGGGGGGGGGGK..',
      '..KKKKKKKKKKK...',
    ],
    // S16 뽀득뽀득 비닐봉지 칩
    vinylchip: [
      '................',
      '..KKK...KKK.....',
      '.KW.WK.KW.WK....',
      '.KW.WK.KW.WK....',
      '.KWWWWKWWWWK....',
      '.KWHWWWWWwWK....',
      'KWWWWGWWWWwWK...',
      'KWHWGWWWGWwWK...',
      'KWWWWWWWWWwWK...',
      'KWWGWWWGWWwwK...',
      'KWWWWWWWWWwwK.K.',
      '.KwwwwwwwwwK.KWK',
      '..KKKKKKKKK.KWGK',
      '.............KK.',
      '................',
      '................',
    ],
    // S17 찐득한 박스 테이프 캔디
    tapecandy: [
      '................',
      '................',
      '................',
      '................',
      '....KKKKKK......',
      '...KTTTTTTK.....',
      '..KTTKKKKTTK....',
      '..KTK....KTK....',
      '..KTK....KTK....',
      '..KTTKKKKTTK....',
      '...KTTTTTTKTK...',
      '....KKKKKKKTTK..',
      '...........KK...',
      '................',
      '................',
      '................',
    ],
    // S18 반짝반짝 은박지 사탕
    foilcandy: [
      '..............H.',
      '.............HHH',
      '..H...........H.',
      '.HHH.KKKKKK.....',
      'KKH.KUUUUUUK..KK',
      'UGKKUHHUUVVVKKGU',
      'HUGKHHUUVVVPVKUB',
      'GHUGUUVVVPPPBGUb',
      'UGHGVVVPPPBBBGbU',
      'GUGKVPPPBBBbbKbG',
      'UGK.KPBBBbbbKKGU',
      'KK..KBBbbbbK..KK',
      '.....KKKKKK.....',
      '................',
      '................',
      '................',
    ],
    // S19 생선 뼈 마카롱
    bonemacaron: [
      '................',
      '................',
      '.....KKKKKK.....',
      '...KKPHPPPPKK...',
      '..KPHPPPPPPPpK..',
      '..KpPPPPPPPppK..',
      '..KKpKpKpKpKKK.K',
      '.KKWGWGWGWGWGKGK',
      'KDGGGGGGGGGGGGGK',
      '.KKWGWGWGWGWGKGK',
      '..KKpKpKpKpKKK.K',
      '..KPPPPPPPPppK..',
      '..KpPPPPPPpppK..',
      '...KKKKKKKKKK...',
      '................',
      '................',
    ],
    // S23 쥐돌이 크림빵
    goldfishjelly: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '...KK.....KK....',
      '..KTTK...KTTK...',
      '..KTTKKKKKTTK...',
      '.KTTTTTTTTTTTK..',
      '.KTKTTTTTTKTTK..',
      '.KTTTTPTTTTTTKW.',
      '..KTTTTTTTTTKWWK',
      '...KKKKKKKKK.KK.',
      '................',
      '................',
      '................',
    ],
    // S28 츄르 샴페인
    churuchamp: [
      '......KKKK......',
      '......KTtK......',
      '....Y..KK..Y....',
      '...Y..W..W..Y...',
      '......KWWK......',
      '......KYYK......',
      '......KYyK......',
      '......KNnK......',
      '.....KNHNnK.....',
      '....KNHNNNnK....',
      '....KOOOOOoK....',
      '....KOWRRWoK....',
      '....KOOOOOoK....',
      '....KNHNNNnK....',
      '....KnNNNnnK....',
      '....KKKKKKKK....',
    ],
    // S29 다이어트 공기 한 조각
    dietair: [
      '................',
      '.......KK.......',
      '......KBUK......',
      '.....KKKKKK.....',
      '...KKUU..UUKK...',
      '..KUH......UUK..',
      '.KUH...Y....UUK.',
      '.KUH..YHY....UK.',
      'KUH....Y.....UUK',
      'KUU..........UUK',
      'KUU..........UBK',
      'KKKKKKKKKKKKKKKK',
      'KWHWWWWWWWWWWWwK',
      '.KwwwwwwwwwwwwK.',
      '..KKKKKKKKKKKK..',
      '................',
    ],
    // S30 황금 고등어 통조림
    goldmackerel: [
      '............Y...',
      '...........YHY..',
      '............Y...',
      '................',
      '..KKKKKKKKKKKK..',
      '.KYHYYYYYYYYYyK.',
      '.KyYYYYYYYYYyyK.',
      'KKKKKKKKKKKKKKKK',
      'KYWWWWWWWWWWWWyK',
      'KYWWbbbbbbWWbWyK',
      'KYWKBBBBBBBBbWyK',
      'KYWWWUUUUUWWbWyK',
      'KYWWWWWWWWWWWWyK',
      'KyyyyyyyyyyyyyyK',
      '.KKKKKKKKKKKKKK.',
      '................',
    ],
    fishgrill: [
      '.....G....G.....',
      '....G....G......',
      '.....G....G.....',
      '...KKKKKKKK..KK.',
      '..KtttCttCtK.KtK',
      '.KtHKtCttCttKKtK',
      'KTTTKTTTTTTTTTK.',
      'KSSSSSSSSSSSSSK.',
      '.KSSSsSSSSsSKKsK',
      '..KKKKKKKKKK.KKK',
      '.KKKKKKKKKKKKKK.',
      'KWWWWWWWWWWWWYYK',
      'KwWWWWWWWWWWWYyK',
      '.KwwwwwwwwwwwwK.',
      '..KKKKKKKKKKKK..',
      '................',
    ],
    tuna: [
      '................',
      '....KKKKKKKK....',
      '...KGWWWWWWGK...',
      '...KGGgGGGGgK...',
      '....KKGGGGKK....',
      '..KKKKKKKKKKKK..',
      '.KGAAAaAAAAaAGK.',
      'KGAaSAAAaAAAAAGK',
      'KGAAAAaAAASAaAGK',
      'KKGGGGGGGGGGGGKK',
      'KBBBBBBBBBBBBBBK',
      'KBHWBBBBBBBBBBbK',
      'KBBBBBBBBBBBBBbK',
      'KGGGGGGGGGGGGGgK',
      '.KKKKKKKKKKKKKK.',
      '................',
    ],
    chicken: [
      '................',
      '................',
      '......K..K......',
      '.....KWKKSK.....',
      '....KWSKSsK.K...',
      '...KWSsKWsKKSK..',
      '..KWSsSWSsSWsK..',
      '..KSsSWSsSWSsK..',
      '.KWSSWSsSWSssSK.',
      '.KSsWSsSWSsSssK.',
      '.KKKKKKKKKKKKKK.',
      'KWWWWWWWWWWWWWwK',
      '.KwwwwwwwwwwwwK.',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
    ],
    salmon: [
      '................',
      '.........N.N....',
      '..........N.....',
      '....KKKKKKKKK...',
      '..KKAHAAWAAAAKK.',
      '.KAHAAWAAAWAAAK.',
      '.KAAAWAAAWAAAaK.',
      'KAAAWAAAWAAAWaaK',
      'KAAWAAAWAAAWAaaK',
      'KaAAAAWAAAWAaaaK',
      '.KDDDDDDDDDDDDK.',
      'KWKKKKKKKKKKKKWK',
      'KwWWWWWWWWWWWWwK',
      '.KwwwwwwwwwwwwK.',
      '..KKKKKKKKKKKK..',
      '................',
    ],
    omurice: [
      '................',
      '................',
      '................',
      '.....KKKKKK.....',
      '...KKYYYYYYKK...',
      '..KYHHYYYYYYEK..',
      '.KYHYRRYRRYYYEK.',
      '.KYYYRRRRRYYYEK.',
      '.KYYYYRRRYYYEEK.',
      '.KEYYYYRYYYEEyK.',
      '.KyEEEEEEEEyyyK.',
      'KWKKKKKKKKKKKKWK',
      'KwWWWWWWWWWWWWwK',
      '.KwwwwwwwwwwwwK.',
      '..KKKKKKKKKKKK..',
      '................',
    ],
    bento: [
      '................',
      '................',
      'KKKKKKKKKKKKKKKK',
      'KRRRRRRRRRRRRRrK',
      'KKKKKKKKKKKKKKKK',
      'KNKNNNNKNKYHYYEK',
      'KKWKNNKWKKYYYYEK',
      'KKWWKKWWKKEEEEyK',
      'KKWWWWWWKKKKKKKK',
      'KKWXWWXWKKnNNnNK',
      'KKWPWWPWKKNNnNnK',
      'KKWWWWWWKKRRRRrK',
      'KNKKKKKKNKrrrrrK',
      'KKKKKKKKKKKKKKKK',
      '.KrrrrrrrrrrrrK.',
      '..KKKKKKKKKKKK..',
    ],
    milk: [
      '................',
      '................',
      '................',
      '................',
      '....KKKKKKKK....',
      '..KKUUUUUUUUKK..',
      '.KUUWWWWWWWWUUK.',
      'KUWWHHWWWWWWWWUK',
      'KBWWWWWWWWWWWwBK',
      'KBBwwWWWWWWwwBBK',
      'KBBBBBBBBBBBBBbK',
      '.KBUBBBBBBBBBbK.',
      '.KBBBBBBBBBBbbK.',
      '..KbBBBBBBBbbK..',
      '...KKbbbbbbKK...',
      '....KKKKKKKK....',
    ],
    tempura: [
      '................',
      '................',
      '................',
      '.KKK........KKK.',
      'KRRRK......KRRRK',
      '.KRrK......KrRK.',
      '.KYHEK....KEHYK.',
      '..KYEyK..KyEYK..',
      '.KKKYEyKKyEYKKK.',
      'KbWWWYEyyEYWWWbK',
      'KBBBBBBBBBBBBBbK',
      '.KBUBBWBBWBBWbK.',
      '.KBUBBBBBBBBBbK.',
      '..KbBBBBBBBBbK..',
      '...KKbbbbbbKK...',
      '....KKKKKKKK....',
    ],
    sushi: [
      '................',
      '................',
      '.............P..',
      '............PQP.',
      '..KKKKK..KKKKKK.',
      '.KYHXYYKKRZRRRrK',
      '.KyYXYyKKrRRRrrK',
      '.KWWXWWKKWHWWWWK',
      '.KWHXWWKKWWWWWwK',
      '.KWWXWwKKWWWWwwK',
      '.KKKKKKKKKKKKKKK',
      'KNNNNnNNNNNnNNNK',
      '.KnNNNNnNNNNNnK.',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
    ],
    ramen: [
      '.....G........KK',
      '....G........KTK',
      '.....G......KTK.',
      '....G......KTK..',
      '....KKKKKKKTK...',
      '..KKRRRRRRRRKK..',
      '.KRRXSsNSWWSSRK.',
      'KRSXWPSWYYWsNSRK',
      'KRSXPWSwWWwSsSRK',
      'KRRsSsNSsSSsSRRK',
      'KRRRRRRRRRRRRRrK',
      '.KRWRRWRRWRRWrK.',
      '.KRRRRRRRRRRrrK.',
      '..KrRRRRRRRrrK..',
      '...KKrrrrrrKK...',
      '....KKKKKKKK....',
    ],
    pouch: [
      '................',
      '...KKKKKKKKKK...',
      '...KGWGWGWGWK...',
      '..KKKKKKKKKKKK..',
      '..KVVHVVVVVVVK..',
      '..KVHVVVVVVVvK..',
      '..KWWWWWWWWWWK..',
      '..KWWAWAAAWWWK..',
      '..KWWAAAAAKAWK..',
      '..KWWAWAAAWWWK..',
      '..KWWWWWWWWWWK..',
      '..KVVVVVVVVVvK..',
      '..KVVVVVVVVvvK..',
      '..KvVVVVVVVvvK..',
      '...KKKKKKKKKK...',
      '................',
    ],
    churu: [
      '......KKKK......',
      '.....KAAHAK..P.P',
      '......KAaK...PPP',
      '.....KWKKWK...P.',
      '.....KOHOOK.....',
      '.....KOHOoK.....',
      '.....KWWWWK.....',
      '.....KWRRWK.....',
      '.....KWRRWK.....',
      '.....KWWWWK.....',
      '.....KOOOoK.....',
      '.....KOOOoK.....',
      '.....KOOooK.....',
      '.....KGgGgK.....',
      '.....KKKKKK.....',
      '................',
    ],
    icecream: [
      '................',
      '.....KKKKKK.....',
      '....KPPPPPPK....',
      '...KPHPPPPPPK...',
      '...KPPPPPPPpK...',
      '...KKKKKKKKKK...',
      '...KWWWWWWWWK...',
      '...KWHWWWWWwK...',
      '...KKKKKKKKKK...',
      '....KTtTTtTK....',
      '....KTTtTTTK....',
      '.....KtTTtK.....',
      '.....KTTTTK.....',
      '......KtTK......',
      '.......KK.......',
      '................',
    ],
    anchovy: [
      '.......KKK......',
      '......KbHBK.....',
      '...KKKKbKBKKKK..',
      '..KbHBKbUBKbHBK.',
      '..KbKBKbUHKbKBK.',
      '..KbUBKbUHKbUBK.',
      '..KbUHKbUHKbUHK.',
      '.KKKKKKKKKKKKKK.',
      '.KTtTtTtTtTtTtK.',
      'KTTTTTTTTTTTTTtK',
      'KTTWWWWWWWWWWTtK',
      'KTTWWbbbWbWWWTtK',
      'KTTWWWWWWWWWWTtK',
      'KTTTTTTTTTTTTTtK',
      'KttttttttttttttK',
      '.KKKKKKKKKKKKKK.',
    ],
  };

  // ---------- 4차 (2026-09-26): 프리미엄 밥 9 + 간식 9. 상점 카드에서 움직인다 ----------
  // 정지 그림(우클릭 메뉴·바닥에 떨어진 먹이)은 첫 프레임. 움직임은 FOOD_ANIM 이 프레임마다 얹는 점들이다
  const steam = (cols, bottom, h, f) => {
    const out = [];
    cols.forEach((c, i) => {
      for (let k = 0; k < h; k++) {
        const s = k + f + i;
        if (s % 3 === 0) continue;
        out.push([c + [0, 1, 1, 0][s % 4], bottom - k, k > h / 2 ? 'G' : 'g']);
      }
    });
    return out;
  };
  const sparkle = (points, f) => {
    const p = points[f % points.length];
    if (!p) return [];
    const [x, y] = p;
    return [[x, y, 'H'], [x - 1, y, 'Y'], [x + 1, y, 'Y'], [x, y - 1, 'Y'], [x, y + 1, 'Y']];
  };
  const rep = (s, n) => s.repeat(Math.max(0, n));
  // 빈 칸 중 색칠된 칸과 맞닿은 곳을 외곽선(K)으로. 코드로 찍는 그림에 쓴다
  const outline = (rows) => {
    const g = rows.map((r) => r.split(''));
    const filled = (x, y) => y >= 0 && y < 16 && x >= 0 && x < 16 && rows[y][x] !== '.' && rows[y][x] !== 'K';
    return g.map((r, y) => r.map((ch, x) => (ch === '.' && (filled(x - 1, y) || filled(x + 1, y) || filled(x, y - 1) || filled(x, y + 1)) ? 'K' : ch)).join(''));
  };

  const PREM = {
    samgyetang: [
      '................',
      '................',
      '................',
      '.....KKKKKK.....',
      '....KSWWSSsK....',
      '...KSWSSSSSsK...',
      '..KKSSSSSSSssKK.',
      '.KUUKsSSSSssKNUK',
      'KUWUUKKKKKKKRNUK',
      'KUUUSsUUUURRUUUK',
      'KKKKKKKKKKKKKKKK',
      'KCCCCCCCCCCCCCcK',
      '.KcCcccccccccXK.',
      '.KccccccccccXXK.',
      '..KKKKKKKKKKKK..',
      '................',
    ],
    otoroOmakase: [
      '................',
      '................',
      '................',
      '.KKKKK..KKKKK...',
      'KQPYPPKKQPYPPK..',
      'KPPQPQKKPPQPQK..',
      'KpPpPpKKpPpPpK..',
      'KWWWWwKKWWWWwK..',
      'KwWWwwKKwWWwwKNN',
      '.KKKKK..KKKKK.nn',
      'KKKKKKKKKKKKKKKK',
      'KXDXXXXXXXXXXXXK',
      'KyYYYYYYYYYYYYyK',
      'KXXXXXXXXXXXXXXK',
      '.KK..........KK.',
      '................',
    ],
    roomService: [
      '................',
      '................',
      '.......KK.......',
      '......KYyK......',
      '....KKKKKKKK....',
      '...KGHHGGGGgK...',
      '..KGHWGGGGGGgK..',
      '.KGHWGGGGGGGGgK.',
      '.KGWGGGGGGGGGgK.',
      '.KGGGGGGGGGGggK.',
      '.KgGGGGGGGGgggK.',
      'KKKKKKKKKKKKKKKK',
      'KWHWWWWWWWWWWWGK',
      '.KGWWWWWWWWWWGK.',
      '..KKKKKKKKKKKK..',
      '................',
    ],
    roomServiceOpen: [
      '..KKKKKKKKK.....',
      '.KGHHGGGGGgK....',
      'KKKKKKKKKKKKK...',
      '................',
      '................',
      '................',
      '................',
      '...KKKKK.KKKK...',
      '..KCcCCCKRZRRK..',
      '.KCCCcCCKRRRrNK.',
      '.KcCCCcCKrRrNnK.',
      'KKKKKKKKKKKKKKKK',
      'KWHWWWWWWWWWWWGK',
      '.KGWWWWWWWWWWGK.',
      '..KKKKKKKKKKKK..',
      '................',
    ],
    firstClassMeal: [
      '................',
      '................',
      '...........KKK..',
      '...........KYK..',
      '...KKKKK...KYK..',
      '..KWWWWWK..KHK..',
      '.KWKKKKKWK.KYK..',
      'KWKCcCCNKWK.K...',
      'KWKcCCNnKWK.K...',
      '.KWKKKKKWK.KKK..',
      '..KWWWWWK.......',
      'KKKKKKKKKKKKKKKK',
      'KbbYbbbbbbbbYbbK',
      'KyyyyyyyyyyyyyyK',
      '.KKKKKKKKKKKKKK.',
      '................',
    ],
    hanwooSteak: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '..KKKKKKKKKK....',
      '.KDgggggggDDK...',
      'KDgKKKKKKKKDDK..',
      'KDKCSCYCSCCKDKKK',
      'KDKCcSCCcSCKDTTK',
      'KDKSCCcSNCcKDKKK',
      'KDgKKKKKKKKDDK..',
      '.KDDDDDDDDDDK...',
      '..KKKKKKKKKK....',
      '................',
      '................',
    ],
    spaceFood: [
      '..Y.............',
      '.YHY.....KKK....',
      '..Y......KbK....',
      '........KWHWK...',
      '........KWBWK...',
      '........KWBWK...',
      '.KKKKKKKKKKKKKK.',
      'KGHGGGGGGGGGGGgK',
      'KGKKKKKKKKKKKKgK',
      'KGKOHOKNNKPQPKgK',
      'KGKOOoKnNKPPpKgK',
      'KGKKKKKKKKKKKKgK',
      'KGGGGGGGGGGGGGgK',
      '.KggggggggggggK.',
      '..KKKKKKKKKKKK..',
      '................',
    ],
    royalTable: [
      '................',
      '................',
      '................',
      '..KKKK....KKKK..',
      '.KWWHWK..KUBUBK.',
      '.KYHYYK..KYHYYK.',
      '.KyYYyK..KyYYyK.',
      'KNnKOoKRZKMmKTtK',
      'KyyKyyKyyKyyKyyK',
      'KKKKKKKKKKKKKKKK',
      'KZRRRRRRRRRRRRRK',
      'KrRYRRRRRRRRYRrK',
      '.KrK........KrK.',
      '.KrK........KrK.',
      '.KKK........KKK.',
      '................',
    ],
    dragonKingFeast: [
      '..K.K.K.........',
      '.KYKYKYK........',
      '.KYYZYYKK.K.....',
      '.KYYYYYKrKrK.KK.',
      '.KRRRRRRRRRKKrrK',
      'KRHKRRRZRRRRrrK.',
      'RRRRRRZRRRZRRrK.',
      'KRRRRRRRRRRRrrK.',
      'KKAAAAAAAAAKKrrK',
      'HKKKKKKKKKKKKKKH',
      'KYBUBBBBBBBBUBYK',
      '.KyyyyyyyyyyyyK.',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
      '................',
    ],
    fortuneCookie: [
      '................',
      '................',
      '.....KKKKKK.....',
      '...KKYYYYYYKK...',
      '..KYYYYYYYYYYK..',
      '.KYHHYYYYYYYEEK.',
      'KYHYYYYYYYYYYEEK',
      'KYYYYYYKKYYYYEyK',
      'EYYYYYKWWKYYYEyy',
      'EYYYYKWRWWKYEEyy',
      'yEYYK.KWWK.KYyyK',
      'KyEK...KK...KyK.',
      '.KK..........K..',
      '................',
      '................',
      '................',
    ],
    mysteryBox: [
      '................',
      '................',
      '....KK....KK....',
      '...KYyK..KyYK...',
      '....KYYKKYYK....',
      '.....KKyyKK.....',
      '.KKKKKKYYKKKKKK.',
      'KVHHVVVYYVVVVVvK',
      'KvvvvvvyyvvvvvvK',
      'KKKKKKKKKKKKKKKK',
      '.KVVVVWWWVVVVvK.',
      '.KVVVVVVVWVVVvK.',
      '.KVVVVVVWVVVVvK.',
      '.KVVVVVVVVVVVvK.',
      '.KvvvvvvWvvvvvK.',
      '.KKKKKKKKKKKKKK.',
    ],
    cloudMallow: [
      '................',
      '................',
      '................',
      '................',
      '.....KKKK.......',
      '....KHWWWK.KK...',
      '..KKKWWWWWKWWK..',
      '.KWHWWWWWWWWWUK.',
      'KWWWWKWWWWKWWWUK',
      'KWWPWWWKKWWPWUUK',
      '.KUWWWWWWWWWUUK.',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
      '................',
      '................',
    ],
    inviteCookie: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '.KKKKKKKKKKKKKK.',
      '.KWSSSSSSSSSSWK.',
      '.KTWTTTTTTTTWtK.',
      '.KTTWRRTTRRWTtK.',
      '.KTTTZRRRRRTTtK.',
      '.KTTTTRRRRTTTtK.',
      '.KtTTTTRRTTTttK.',
      '.KttttttttttttK.',
      '.KKKKKKKKKKKKKK.',
      '................',
      '................',
    ],
    dragonCandy: [
      '................',
      '................',
      '................',
      '................',
      '.....KKKKKK.....',
      '....KRRZRRrK....',
      '...KRZHRRRRrK...',
      '...KRRYYYYRrK...',
      '...KRYRRRYRrK...',
      '...KRYRYYRYrK...',
      '....KrRRRYrK....',
      '.....KKKKKK.....',
      '.....KPKWKPK....',
      '.......KW.......',
      '.......KW.......',
      '.......KK.......',
    ],
    goldMouseChoco: [
      '................',
      '................',
      '................',
      '.......KKKK.....',
      '......KYPPyK....',
      '......KYPPyK....',
      '.....KKKYYyKK...',
      '...KKYYHYYYYYK..',
      '..KYYKYYHYYYYyK.',
      'gKYYYYYYYYYYyyK.',
      'KPYYYYYYYYYyyyK.',
      'gKKyyyyyyyyyyK..',
      '..KTtTtTtTtTtK..',
      '...KtTtTtTtTK...',
      '....KKKKKKKK....',
      '................',
    ],
  };

  // 츄르 마카롱 10개 피라미드 (1·2·3·4)
  PREM.macaronTower = (() => {
    const g = Array.from({ length: 16 }, () => Array(16).fill('.'));
    const cols = [['P', 'p'], ['M', 'm'], ['Y', 'y'], ['V', 'v'], ['A', 'a'], ['B', 'b'], ['Q', 'P'], ['N', 'n'], ['P', 'p'], ['Y', 'y']];
    let i = 0;
    [[6], [4, 8], [2, 6, 10], [0, 4, 8, 12]].forEach((xs, lv) => {
      xs.forEach((x0) => {
        const [c, d] = cols[i++];
        const y0 = 1 + lv * 3;
        g[y0][x0 + 1] = c; g[y0][x0 + 2] = c; g[y0][x0 + 3] = c;
        g[y0][x0 + 1] = 'H';
        g[y0 + 1][x0 + 1] = 'W'; g[y0 + 1][x0 + 2] = 'W'; g[y0 + 1][x0 + 3] = 'W';
        g[y0 + 2][x0 + 1] = d; g[y0 + 2][x0 + 2] = d; g[y0 + 2][x0 + 3] = d;
      });
    });
    for (let x = 0; x < 16; x++) g[13][x] = x === 0 || x === 15 ? '.' : x < 3 || x > 12 ? 'y' : 'Y';
    return outline(g.map((r) => r.join('')));
  })();

  // 애프터눈 티 3단 트레이: 딸기 케이크 / 마카롱 셋 / 스콘·오이 샌드위치
  PREM.afternoonTea = [
    '.......KK.......',
    '......KYYK......',
    '......KRRK......',
    '.....KWQQWK.....',
    '....KWWWWWWK....',
    '.....KKyyKK.....',
    '...KPPKMMKYYK...',
    '...KppKmmKyyK...',
    '..KWWWWWWWWWWK..',
    '...KKKKyyKKKK...',
    '.KTTKNWNKTTKNWK.',
    '.KttKSSSKttKSSK.',
    'KWWWWWWWWWWWWWWK',
    '.KKKKKKyyKKKKKK.',
    '......KYYK......',
    '.....KKKKKK.....',
  ];

  // 참치 아이스크림 5단콘: 스쿱마다 아래가 볼록해서 층이 보인다
  PREM.tunaCone = [
    '.....KKKKKK.....',
    '....KQPPPPpK....',
    '...KpPpPpPppK...',
    '....KSAAAAaK....',
    '...KaAaAaAaaK...',
    '....KWWWWWGK....',
    '...KGWGWGWGGK...',
    '....KQPPPPpK....',
    '...KpPpPpPppK...',
    '....KMMMMMmK....',
    '...KmMmMmMmmK...',
    '...KKKKKKKKKK...',
    '....KTtTtTtK....',
    '.....KtTtTK.....',
    '......KTtK......',
    '.......KK.......',
  ];

  // 회전초밥: 접시 셋이 벨트를 따라 흐른다 (연어·참치·계란)
  const sushiTrainFrame = (f) => {
    const g = Array.from({ length: 16 }, () => Array(16).fill('.'));
    const put = (x, y, ch) => { if (x >= 0 && x < 16 && y >= 0 && y < 16 && ch !== '.') g[y][x] = ch; };
    // 뒤쪽 벽의 빨간 포렴
    for (let x = 0; x < 16; x++) { put(x, 0, 'K'); put(x, 1, x % 4 === 3 ? 'K' : 'R'); put(x, 2, x % 4 === 3 ? '.' : x % 4 === 1 ? 'W' : 'R'); put(x, 3, x % 4 === 3 ? '.' : 'K'); }
    for (let x = 0; x < 16; x++) {
      put(x, 9, 'K');
      put(x, 10, (x + f) % 3 === 0 ? 'g' : 'G');
      put(x, 11, 'D');
      put(x, 12, 'K');
    }
    put(1, 13, 'K'); put(1, 14, 'K'); put(14, 13, 'K'); put(14, 14, 'K');
    const fish = [['O', 'W', 'o'], ['R', 'Z', 'r'], ['Y', 'X', 'y']];
    fish.forEach(([c, s, d], i) => {
      const x0 = ((f + i * 7) % 21) - 4;
      ['.KKKK.', 'K' + c + s + c + d + 'K', 'KWWWwK', 'KKKKKK', 'bBBBBb'].forEach((row, dy) => {
        [...row].forEach((ch, dx) => put(x0 + dx, 4 + dy, ch));
      });
    });
    return g.map((r) => r.join(''));
  };

  const FOOD_ANIM = {
    samgyetang: { frames: 6, ms: 220, draw: (f) => ({ px: steam([5, 9], 2, 3, f) }) },
    otoroOmakase: { frames: 4, ms: 350, draw: (f) => ({ px: sparkle([[3, 4], null, [10, 4], null], f) }) },
    roomService: { frames: 8, ms: 380, draw: (f) => {
      const seq = ['c', 'c', 'c', 'semi', 'open', 'open', 'open', 'semi'][f];
      if (seq === 'c') return { rows: PREM.roomService, px: f === 1 ? sparkle([[4, 7]], 0) : [] };
      if (seq === 'open') return { rows: PREM.roomServiceOpen, px: steam([5, 11], 6, 4, f) };
      const rows = PREM.roomServiceOpen.map((r, y) => (y >= 7 ? r : rep('.', 16)));
      for (let y = 3; y <= 10; y++) rows[y - 3] = PREM.roomService[y];
      return { rows };
    } },
    firstClassMeal: { frames: 6, ms: 260, draw: (f) => ({ px: [...steam([4, 6], 3, 3, f), [12, 6 - (f % 3), 'H']] }) },
    sushiTrain: { frames: 21, ms: 160, draw: (f) => ({ rows: sushiTrainFrame(f) }) },
    hanwooSteak: { frames: 6, ms: 200, draw: (f) => {
      const pops = [[[3, 5, 'Y'], [11, 4, 'H']], [[6, 4, 'H'], [13, 6, 'Y']], [[2, 6, 'Y'], [9, 3, 'Y']]][f % 3];
      return { px: [...steam([5, 8], 4, 4, f), ...pops] };
    } },
    royalTable: { frames: 6, ms: 230, draw: (f) => ({ px: [...steam([3, 11], 2, 3, f), ...sparkle([[4, 5], null, null, [12, 5], null, null], f)] }) },
    mysteryBox: { frames: 8, ms: 150, draw: (f) => ({ dx: [0, -1, 1, -1, 1, 0, 0, 0][f], dy: [0, 0, 0, 0, 0, 0, -1, 0][f], px: f >= 5 ? sparkle([[2, 3]], 0) : [] }) },
    cloudMallow: { frames: 8, ms: 220, draw: (f) => ({ dy: [0, -1, -1, -1, 0, 0, 0, 0][f], px: sparkle([[2, 2], null, null, [14, 12], null, null, null, null], f) }) },
    tunaCone: { frames: 6, ms: 260, draw: (f) => {
      const d = [];
      for (let k = 0; k <= Math.min(f, 3); k++) d.push([12, 11 + k, k === Math.min(f, 3) ? 'p' : 'P']);
      return { px: f < 5 ? d : [] };
    } },
    macaronTower: { frames: 6, ms: 280, draw: (f) => {
      const sway = [0, 1, 0, -1, 0, 0][f];
      const rows = PREM.macaronTower.map((r, y) => (y < 5 && sway ? (sway > 0 ? '.' + r.slice(0, 15) : r.slice(1) + '.') : r));
      return { rows, px: sparkle([null, [13, 3], null, null, [2, 5], null], f) };
    } },
    inviteCookie: { frames: 6, ms: 260, draw: (f) => {
      const px = [];
      if (f % 3 === 1) px.push([5, 7, 'Z'], [10, 7, 'Z'], [4, 9, 'Z'], [11, 9, 'Z'], [7, 12, 'Z'], [8, 12, 'Z']);
      const hy = 4 - f;
      if (hy >= 0) px.push([12, hy, 'P'], [14, hy, 'P'], [13, hy + 1, 'P']);
      return { px };
    } },
    afternoonTea: { frames: 6, ms: 280, draw: (f) => ({ px: [...(f % 3 === 0 ? [[7, 1, 'E'], [8, 1, 'E']] : []), [7, 2, f % 2 ? 'Z' : 'R'], ...sparkle([[1, 5], null, [14, 3], null, [14, 9], null], f)] }) },
    dragonCandy: { frames: 4, ms: 150, draw: (f) => {
      const F = [
        [[6, 3, 'R'], [7, 3, 'O'], [8, 3, 'O'], [9, 3, 'R'], [7, 2, 'O'], [8, 2, 'Y'], [7, 1, 'Y'], [8, 0, 'R']],
        [[6, 3, 'R'], [7, 3, 'O'], [8, 3, 'O'], [9, 3, 'R'], [7, 2, 'Y'], [8, 2, 'O'], [8, 1, 'Y'], [7, 0, 'R']],
        [[6, 3, 'O'], [7, 3, 'Y'], [8, 3, 'O'], [9, 3, 'R'], [6, 2, 'R'], [7, 2, 'O'], [8, 2, 'E'], [7, 1, 'O'], [6, 0, 'R']],
        [[6, 3, 'R'], [7, 3, 'O'], [8, 3, 'Y'], [9, 3, 'O'], [8, 2, 'O'], [9, 2, 'R'], [8, 1, 'E'], [9, 0, 'R']],
      ];
      return { px: F[f] };
    } },
    goldMouseChoco: { frames: 6, ms: 240, draw: (f) => {
      const tail = f % 2 ? [[15, 10, 'y'], [15, 9, 'y'], [15, 8, 'y'], [14, 7, 'y']] : [[15, 10, 'y'], [15, 11, 'y'], [15, 12, 'y'], [14, 13, 'y']];
      return { px: [...tail, ...sparkle([[7, 7], null, [11, 9], null, [5, 10], null], f)] };
    } },
  };
  for (const k of Object.keys(FOOD_ANIM)) FOOD[k] = k === 'sushiTrain' ? sushiTrainFrame(0) : PREM[k];
  // 10-10 디자인 개선: 그림을 새로 그리면서 움직임을 뺀 프리미엄 먹이 (좌표가 새 그림과 안 맞아서). 그림만 그대로 쓴다
  for (const k of ['spaceFood', 'dragonKingFeast', 'fortuneCookie']) FOOD[k] = PREM[k];

  // 움직이는 먹이의 f 번째 프레임 (줄 문자열 배열). 움직임이 없으면 그대로
  function frameRows(name, f) {
    const a = FOOD_ANIM[name];
    if (!a) return FOOD[name];
    const o = a.draw(f % a.frames) || {};
    const base = o.rows || FOOD[name];
    const g = Array.from({ length: 16 }, () => Array(16).fill('.'));
    const dx = o.dx || 0, dy = o.dy || 0;
    const put = (x, y, ch) => { x += dx; y += dy; if (ch !== '.' && x >= 0 && y >= 0 && x < 16 && y < 16) g[y][x] = ch; };
    base.forEach((r, y) => [...r].forEach((ch, x) => put(x, y, ch)));
    (o.px || []).forEach(([x, y, ch]) => put(x, y, ch));
    return g.map((r) => r.join(''));
  }

  // 장난감 — 상점 카드·우클릭 메뉴·바닥에 던진 장난감이 이 그림을 쓴다. 먹이처럼 16×16 에 음영 두 톤
  const TOY = {
    ball: [
      '................',
      '.....KKKKKK.....',
      '...KKRRRRRRKK...',
      '..KRRHHRRRRRRK..',
      '..KRHHRRRRRRrK..',
      '.KRRHRRRRRRRRrK.',
      '.KWWWWWWYWWWWwK.',
      '.KWWWWWYYYWWWwK.',
      '.KRRRRRRYRRRRrK.',
      '.KRRRRRRRRRRrrK.',
      '..KRRRRRRRRrrK..',
      '..KrRRRRRRrrrK..',
      '...KKrrrrrrKK...',
      '.....KKKKKK.....',
      '................',
      '................',
    ],
    yarn: [
      '................',
      '.....KKKKKK.....',
      '...KKPpPPPpKK...',
      '..KPPpPPPpPPPK..',
      '..KPpPPPpPPPpK..',
      '.KPpPPPpPPPpPPK.',
      '.KpPPPpPPPpPPpK.',
      '.KPPPpPPPpPPpPK.',
      '.KPPpPPPpPPpPPK.',
      '.KPpPPPpPPpPPpK.',
      '..KPPPpPPpPPpK..',
      '..KpPpPPpPPpPK..',
      '...KKpPPpPpKKp..',
      '.....KKKKKK..p..',
      '............p.p.',
      '..............p.',
    ],
    mouse: [
      '................',
      '................',
      '................',
      '.......KKK......',
      '......KPPPK.....',
      '.....KKPPPK.....',
      '...KKGGKKKGKK...',
      '..KGGGGGGGGGGK..',
      '.KGKGGGGGGGGGgK.',
      'KPGGGGGGGGGGGgK.',
      '.KKGGGGGGGGGggK.',
      '...KKgggggggKK.K',
      '.....KKKKKKK..K.',
      '............KK..',
      '................',
      '................',
    ],
    catnip: [
      '................',
      '................',
      '................',
      '................',
      '...KKKKKKKK.....',
      '..KNNNNNNNNKK.KK',
      '.KNKNnNNnNNNNKNK',
      'KNNNNNnNNnNNNNNK',
      'KQNNnNNnNNNNNKNK',
      '..KnnnnnnnnKK.KK',
      '...KKKKKKKK.....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    wand: [
      '...........KKK..',
      '..........KCK.g.',
      '.........KCK..g.',
      '........KCK...g.',
      '.......KCK....g.',
      '......KCK.....g.',
      '.....KCK......g.',
      '....KCK.......g.',
      '...KRK......KgK.',
      '..KRRK.....KBBK.',
      '.KRRK.....KBHBBK',
      '..KK......KBBBBK',
      '..........KbBBbK',
      '...........KbbK.',
      '..........KB..BK',
      '..........KK..KK',
    ],
    feather: [
      '.........KK.....',
      '........KPPK.KK.',
      '.......KPPPKKBBK',
      '.......KPPPKBBBK',
      '......KKPPKBBBK.',
      '.....KYYKKKBBK..',
      '....KYYYYKKKK...',
      '....KYYYKK......',
      '.....KKKDK......',
      '.......KDK......',
      '......KDK.......',
      '.....KDK........',
      '....KRK.........',
      '...KRRK.........',
      '..KRRK..........',
      '...KK...........',
    ],
    jingle: [
      '................',
      '.....KKKKKK.....',
      '...KKYYYYYYKK...',
      '..KYYHHYYYYYyK..',
      '..KYHHYYYYYYyK..',
      '.KYYHYYYYYYYYyK.',
      '.KYYYYYYYYYYYyK.',
      '.KKKKKKKKKKKKKK.',
      '.KYYYYKKKKYYYyK.',
      '.KYYYYYKKYYYyyK.',
      '..KYYYYYYYYyyK..',
      '..KyYYYYYYyyyK..',
      '...KKyyyyyyKK...',
      '.....KKKKKK.....',
      '................',
      '................',
    ],
    windup: [
      '................',
      '................',
      '.....KKK.KKK....',
      '.....KYYKYyK....',
      '......KKYKK.....',
      '.......KyK......',
      '..KKK.KKKKKK....',
      '.KPPKKGGGGGGKK..',
      '.KPKGGHGGGGGGgK.',
      'KGKGGGGGGGGGGgK.',
      'PGGGGGGGGGGGggK.',
      '.KKGGGGGGGGggK.K',
      '...KKggggggKK.K.',
      '....KDK..KDKK...',
      '.....K....K.....',
      '................',
    ],
    bubbles: [
      '..........bbbb..',
      '.........bH...b.',
      '.........b....b.',
      '.........b....b.',
      '..........bbbb..',
      '.....bb.........',
      '....bH.b........',
      '....b..b..bb....',
      '.....bb..bH.b...',
      '..KKKK...b..b...',
      '.KUUUUK...bb....',
      '.KUUUUK.........',
      '..KKKK..........',
      '..KB............',
      '.KB.............',
      'KB..............',
    ],
    scratcher: [
      '................',
      '................',
      '................',
      '................',
      '................',
      'KK............KK',
      'KSKK...Nn...KKSK',
      'KTSSKK.nN.KKSStK',
      'KTtTSSKKKKSStTtK',
      'KTtTtTSSSStTtTtK',
      'KTtTtTtTtTtTtTtK',
      'KTtTtTtTtTtTtTtK',
      'KCCCCCCCCCCCCCCK',
      'KKKKKKKKKKKKKKKK',
      '................',
      '................',
    ],
    bag: [
      '................',
      '................',
      '................',
      '................',
      '....KKKKKKKKKKK.',
      '..KKwKSSSsSSSSK.',
      '.KcccKSSSsSSSSK.',
      'KccccKSSSsSSSsK.',
      'KYcYcKSSSsSSSsK.',
      'KccccKSSSsSSSsK.',
      'KccccKsSSsSSSsK.',
      '.KcccKssssssssK.',
      '..KKwKssssssssK.',
      '....KKKKKKKKKKK.',
      '................',
      '................',
    ],
    box: [
      '................',
      '................',
      '................',
      'KSSK.KKKKKK.KSSK',
      '.KSTKccccccKTSK.',
      '..KKKKKKKKKKKK..',
      '..KSSSSwwSSSSK..',
      '..KTTTTwwTTTtK..',
      '..KTCTTwwTTTtK..',
      '..KCCCTTTTTTtK..',
      '..KTCTTTTTCTtK..',
      '..KTTTTTTTCCtK..',
      '..KTTTTTTTTTtK..',
      '..KttttttttttK..',
      '..KKKKKKKKKKKK..',
      '................',
    ],
    laser: [
      '................',
      '.......P...P...P',
      '........QQQQ..P.',
      '.......QPPPPQ...',
      '......QPRRRRPQ..',
      '.....PQPRHRRPQPP',
      '......QPRRRRPQ..',
      '......QPRRRrPQ..',
      '.......QPPPPQ...',
      '......P.QQQQ.P..',
      '.....R.....P...P',
      '..KKR...........',
      '.KGRK...........',
      'KGHgK...........',
      'KHgK............',
      'KKK.............',
    ],
    // ---------- 장난감 2차 (2026-09-22) ----------
    // 수류탄 장난감
    grenade: [
      '..........KKK...',
      '.........KY.YK..',
      '......KKKKKYK...',
      '.....KgggggKK...',
      '.....KDDDDDK....',
      '....KKKKKKKKK...',
      '...KNNHNNNNNNK..',
      '..KNHNnNNnNNnNK.',
      '..KNNNNNNNNNNNK.',
      '..KnNNnNNnNNnNK.',
      '..KNNNNNNNNNNNK.',
      '..KnNNnNNnNNnNK.',
      '..KNNNNNNNNNNnK.',
      '...KnnNnnNnnnK..',
      '....KKKKKKKKK...',
      '................',
    ],
    // 물총
    squirtgun: [
      '................',
      '................',
      '......KKKK......',
      '.....KYYYYK.....',
      '.....KYHYyK.....',
      '..KKKKKKKKKKKK..',
      '.KBBBBBBBBBBBBKK',
      '.KBHHBBBBBBBBBBK',
      '.KBBBBBBBBBBBBKK',
      '.KbBBBBKKKKKKK..',
      '.KbBBBK.K.......',
      '.KbBBBKKbK......',
      '.KbBBBK.KK......',
      '.KbBBBK.........',
      '..KKKK..........',
      '................',
    ],
    // 뿅망치
    // 풍선
    balloon: [
      '.....KKKKK......',
      '....KRRRRRK.....',
      '...KRRHHRRRK....',
      '..KRRHRRRRRRK...',
      '..KRRRRRRRRRK...',
      '..KRRRRRRRRRK...',
      '..KRRRRRRRRrK...',
      '...KRRRRRRrK....',
      '....KRRRRrK.....',
      '.....KKrKK......',
      '......KrK.......',
      '.......g........',
      '......g.........',
      '.......g........',
      '........g.......',
      '.......g........',
    ],
    // 요요
    yoyo: [
      '.......g........',
      '.......g........',
      '.......g........',
      '.....KKKKK......',
      '...KKRRRRRKK....',
      '..KRRHRRRRRRK...',
      '..KRHRKKKRRRK...',
      '.KRRRKWWWKRRRK..',
      '.KRRRKWHWKRRRK..',
      '.KRRRKWWWKRRRK..',
      '..KRRRKKKRRrK...',
      '..KRRRRRRRrrK...',
      '...KKrrrrrKK....',
      '.....KKKKK......',
      '................',
      '................',
    ],
    // 드론
    // 책상 위 컵
    cup: [
      '................',
      '................',
      '...KKKKKKKKK....',
      '...KBBBBBBBK....',
      '...KWWWWWWWKKK..',
      '...KWHWWWWWK.K..',
      '...KWHWPWPWK.K..',
      '...KWWWPPWWKKK..',
      '...KWWWWWWWK....',
      '....KWWWWWK.....',
      '....KKKKKKK.....',
      '..KKKKKKKKKKK...',
      '..KTTTTTTTTTK...',
      '..KtttttttttK...',
      '................',
      '................',
    ],
    // 휴지 롤
    // 바나나 껍질
    bananapeel: [
      '.......KKK......',
      '......KWWSK.....',
      '.....KWWWSK.....',
      '.....KWWWSK.....',
      '.....KWWWSK.....',
      '..KK.KWWWSK.KK..',
      '.KYYKKWWWSKKYYK.',
      'KYYyYKYYYYKYyYYK',
      'KYyK.KYHYYK.KyYK',
      'KYyK.KYYYyK.KyYK',
      'KyyK.KYYCyK.KyyK',
      '.KK..KYCYyK..KK.',
      '.....KYYyyK.....',
      '......KyyK......',
      '......KCcK......',
      '.......KK.......',
    ],
    // 놀이 중 바닥에 놓는 껍질은 예전 그림 그대로 (10-10: 상점 그림만 반쯤 깐 바나나로 바꿨다)
    bananapeelFloor: [
      '................',
      '.......KK.......',
      '......KCK.......',
      '......KYK.......',
      '.....KYYyK......',
      '....KYYYYyK.....',
      '...KYHSSSYyK....',
      '..KYYSWWWSYyK...',
      '.KYYKSWWWSKYyK..',
      'KYYK.KSWSK.KYyK.',
      'KYK..KSSSK..KyK.',
      'KyK...KSK...KyK.',
      '.K....KyK....K..',
      '.......K........',
      '................',
      '................',
    ],
    // 캣휠
    catwheel: [
      '.....KKKKK......',
      '...KKTTTTTKK....',
      '..KTTKKKKKTTK...',
      '.KTKK..K..KKTK..',
      '.KTK...K...KTK..',
      'KTK....K....KTK.',
      'KTK....K....KTK.',
      'KTKKKKKKKKKKKTK.',
      'KTK....K....KTK.',
      'KTK....K....KTK.',
      '.KTK...K...KTK..',
      '.KTKK..K..KKTK..',
      '..KTTKKKKKTTK...',
      '...KKTTTTTKK....',
      '....KtK..KtK....',
      '...KttK..KttK...',
    ],
    // 진공청소기
    vacuum: [
      '................',
      '......KKKK......',
      '.....KgggGK.....',
      '....KgKKKKgK....',
      '....KgK...KgK...',
      '..KKKgKK...KDK..',
      '.KRRRRRRK..KDK..',
      'KRHRRRRRrK.KDK..',
      'KRRRRRRRrK.KDK..',
      'KRWWWWWRrK.KDK..',
      'KRRRRRRRrK.KDK..',
      'KrrrrrrrrK.KDK..',
      '.KKKKKKKK.KKKKKK',
      '..KDK.KDK.KDDDDK',
      '...K...K..KKKKKK',
      '................',
    ],
    // 박스 탑
    boxtower: [
      '.....KKKKKK.....',
      '.....KTTTTK.....',
      '.....KTttTK.....',
      '.....KKKKKK.....',
      '...KKKKKKKKKK...',
      '...KTTTTTTTTK...',
      '...KTTTttTTTK...',
      '...KTTTTTTTTK...',
      '...KKKKKKKKKK...',
      '.KKKKKKKKKKKKKK.',
      '.KTTTTTTTTTTTTK.',
      '.KTTTTTttTTTTTK.',
      '.KTTTTTTTTTTTTK.',
      '.KtTTTTTTTTTTtK.',
      '.KKKKKKKKKKKKKK.',
      '................',
    ],
    // 마술 모자
    magichat: [
      '....KK.KK.....Y.',
      '...KWPKWPK...YHY',
      '...KWPKWPK....Y.',
      '...KWWKWWK......',
      '..KKKKKKKKK..HK.',
      '..KXXXXXXXK.KK..',
      '..KXDXXXXXKKK...',
      '..KXDXXXXXKK....',
      '..KXXXXXXXK.....',
      '..KRRRRRRRK.....',
      '..KrrrrrrrK.....',
      'KKKKKKKKKKKKK...',
      'KXXXXXXXXXXXK...',
      '.KKKKKKKKKKK....',
      '................',
      '................',
    ],
    // 고양이 슬롯머신
    slotmachine: [
      '..............KK',
      '.KKKKKKKKKKKK.KR',
      'KRRHRRRRRRRRRKKK',
      'KKKKKKKKKKKKKK.K',
      'KYKKKKKKKKKKYK.K',
      'KYKWWKWWKWWKYK.K',
      'KYKZWKNWKBWKYKKK',
      'KYKWWKWWKWWKYKK.',
      'KYKKKKKKKKKKYK..',
      'KYYYYYYYYYYYYK..',
      'KYHYYKKKKYYYYK..',
      'KYYYYKDDKYYYyK..',
      'KyyyyKKKKyyyyK..',
      'KKKKKKKKKKKKKK..',
      '.KDK......KDK...',
      '................',
    ],
    // 눈덩이
    snowball: [
      '................',
      '................',
      '.....KKKKK......',
      '...KKWWWWWKK....',
      '..KWWHHWWWUWK...',
      '..KWHWWWWWWWK...',
      '.KWWWWWUWWWWUK..',
      '.KWWWWWWWWWWWK..',
      '.KWUWWWWWWWWWK..',
      '.KWWWWWWUWWWUK..',
      '..KWWWWWWWWUK...',
      '..KUWWWWWWUUK...',
      '...KKUUUUUKK....',
      '.....KKKKK......',
      '................',
      '................',
    ],
    // RC 쥐 자동차
    rccar: [
      '................',
      '...........g....',
      '..........g.....',
      '....KK...g......',
      '...KPPK.g.......',
      '..KKGGKKKK......',
      '.KGGGGGGGGKK....',
      'KGGGGGGGGKGGK...',
      'KGGGGGGGGGGGPK..',
      'KKKKKKKKKKKKKK..',
      '.KDDK....KDDK...',
      '.KDDK....KDDK...',
      '..KK......KK....',
      '................',
      '................',
      '................',
    ],
    // UFO 장난감
    ufotoy: [
      '................',
      '......KKKK......',
      '.....KUUUUK.....',
      '....KUHUUUUK....',
      '....KUUUUUUK....',
      '.KKKKKKKKKKKKKK.',
      'KgYgRgYgRgYgRgYK',
      '.KKKKKKKKKKKKKK.',
      '....M......M....',
      '...M...MM...M...',
      '..M....MM....M..',
      '.M.....MM.....M.',
      '................',
      '................',
      '................',
      '................',
    ],
    // 방울 달린 막대 새
    // 공 발사기
    ballshooter: [
      '...........KKK..',
      '..........KRHRK.',
      '..........KRRrK.',
      '...........KKK..',
      '.......KK.g.....',
      '.......KDDK.g...',
      '......KDgDK.....',
      '.....KDgDK......',
      '....KDgDK.......',
      '..KKKKKKKKKK....',
      '.KBBBBBBBBBBK...',
      '.KBHBBBYYBBbK...',
      '.KbbbbbbbbbbK...',
      '..KDK....KDK....',
      '...K......K.....',
      '................',
    ],
    // 줄넘기
    jumprope: [
      '................',
      '....KKKKKKKK....',
      '..KKOYOOYOOOKK..',
      '.KOOKKKKKKKKOOK.',
      'KOYK........KYOK',
      'KOK..........KOK',
      'KOK..........KOK',
      'KYOK........KOYK',
      '.KOOKK....KKOOK.',
      '..KKOOK..KOOKK..',
      '....KKOKKOKK....',
      '....KWK..KWK....',
      '...KBHK..KHBK...',
      '..KBHBK..KBHBK..',
      '.KBBbK....KbBBK.',
      '.KKKK......KKKK.',
    ],
    // 고양이 전용 노트북
    catlaptop: [
      '................',
      '..KKKKKKKKKKK...',
      '..KDDDDDDDDDK...',
      '..KDMMMMMMMDK...',
      '..KDMKKMMMMDK...',
      '..KDMMMMKMMDK...',
      '..KDMMMMMMMDK...',
      '..KDMPMPMMMDK...',
      '..KDMMPMMMMDK...',
      '..KDDDDDDDDDK...',
      '.KKKKKKKKKKKKK..',
      'KgGgGgGgGgGgGgK.',
      'KGgGgGgGgGgGgGK.',
      'KKKKKKKKKKKKKKK.',
      '................',
      '................',
    ],
    // ---------- 3차 (2026-09-24): 함께 하는 놀이 ----------
    // 두더지 잡기 (구멍에서 빼꼼한 고양이와 뿅망치)
    whackcat: [
      '................',
      '..........KKKKK.',
      '.........KRRRRRK',
      '.........KRHRRRK',
      '.........KrrrrrK',
      '..........KKYKK.',
      '...........KYK..',
      '..K...K....KYK..',
      '.KOK.KOK...KYK..',
      '.KOOKOOK...KKK..',
      '.KOOOOOK........',
      '.KOKOKOK........',
      '.KOOPOOK........',
      'KCCCCCCCCK......',
      'KcCTCCCTcK......',
      '.KKKKKKKK.......',
    ],
    // 가위바위보
    rps: [
      '.KK.......KK....',
      'KWSK.....KWSK...',
      '.KSSK...KSSK....',
      '..KSSK.KSSK.....',
      '...KSSKSSK......',
      '...KSSSSSKK.....',
      '..KKSSSSSSSK....',
      'KKKSSSSSSSSK....',
      'KSSKSSSSSSsK....',
      '.KSSSSSSSSsK....',
      '..KSSSSSSssK....',
      '...KKKKKKKKK....',
      '...KBBBBBBbK....',
      '...KBBBBBBbK....',
      '...KKKKKKKKK....',
      '................',
    ],
    // 도미노
    domino: [
      '...........KKKK.',
      '..........KGGGgK',
      '.......KKKKGGGgK',
      '......KWWWGKGDgK',
      '..KKKKKWWWGKGGgK',
      '.KHWWwKWKWGKGGgK',
      '.KWWWwKWWWGKKKKK',
      '.KWKWwKWWWGKGGgK',
      '.KWWWwKKKKKKGDgK',
      '.KWWWwKWWWGKGGgK',
      '.KKKKKKWWKGKGGgK',
      '.KWWWwKWWWGKKKK.',
      '.KWWKwKWKWGK....',
      '.KWWWwKKKKK.....',
      '.KWWWwK.........',
      '..KKKK..........',
    ],
    // 줄다리기
    tugrope: [
      '................',
      '................',
      '................',
      '................',
      's......KK......s',
      '.sKKKKKHrKKKKKs.',
      'KSTCSsTRrsTtCsSK',
      'sStCsTtRrTtSCTSs',
      'KSSCTtSRrtSsCtSK',
      '.sKKKKKRrKKKKKs.',
      's....KRKKRK....s',
      '.....KRKKrK.....',
      '....KRK..KRK....',
      '....KrK..KrK....',
      '.....K....K.....',
      '................',
    ],
    // 트램펄린
    trampoline: [
      '......K..K......',
      '.....KOKKOK.....',
      '.....KOOOOK.....',
      '.....KKOOKK.....',
      '.....KOOOOK.....',
      '......KKKK......',
      '....Y......Y....',
      '................',
      '..KXXXXXXXXXXK..',
      '.KBBBBBBBBBBBBK.',
      '.KbHbbbbbbbbHbK.',
      '..KKKKKKKKKKKK..',
      '..KgK......KgK..',
      '.KgK........KgK.',
      'KKKK........KKKK',
      '................',
    ],
  };

  // 깜짝 이벤트로 줍는 하찮은 보물 (main/treasure.js) 과 보물을 떨어뜨리고 가는 새. 먹이 팔레트를 쓴다
  const TREASURE = {
    // ---------- 7차 (2026-09-23): 하찮은 공작 재료 10종 ----------
    lonesock: [
      '............',
      '...KKKKK....',
      '...KRRRK....',
      '...KWWWK....',
      '...KRRRK....',
      '...KWWWK....',
      '...KWWWKK...',
      '...KWWWWWK..',
      '...KRWWWWWK.',
      '....KRRRRRK.',
      '.....KKKKK..',
      '............',
    ],
    bubblewrap: [
      '............',
      'KKKKKKKKKKKK',
      'KUHUKUHUKUHK',
      'KUUUKUUUKUUK',
      'KKKKKKKKKKKK',
      'KUHUKUHUKUHK',
      'KUUUKUUUKUUK',
      'KKKKKKKKKKKK',
      'KUHUKGGGKUHK',
      'KUUUKGGGKUUK',
      'KKKKKKKKKKKK',
      '............',
    ],
    drinkstraw: [
      '....KKKKKKK.',
      '...KGgRRWWRK',
      '..KgGgWWRRWK',
      '..KGgKKKKKK.',
      '..KgGK......',
      '..KRRK......',
      '..KWWK......',
      '..KRRK......',
      '..KWWK......',
      '..KRRK......',
      '..KWWK......',
      '..KKKK......',
    ],
    pinecone: [
      '............',
      '.....KK.....',
      '....KCCK....',
      '...KCtCtK...',
      '...KtCtCK...',
      '..KCtCtCtK..',
      '..KtCtCtCK..',
      '..KCtCtCtK..',
      '...KtCtCK...',
      '...KCtCtK...',
      '....KKKK....',
      '............',
    ],
    bandaid: [
      '............',
      '............',
      '............',
      '..KKKKKKKK..',
      '.KSsSKKSsSK.',
      'KSSSKWWKSSSK',
      'KSsSKWWKSsSK',
      '.KSSSKKSSSK.',
      '..KKKKKKKK..',
      '............',
      '............',
      '............',
    ],
    googlyeye: [
      '............',
      '...KKKKKK...',
      '..KWWWWWWK..',
      '.KWWWWWWWWK.',
      '.KWWWWWKKWK.',
      '.KWWWWKKKKK.',
      '.KWWWWKHKKK.',
      '.KWWWWWKKWK.',
      '.KWWWWWWWWK.',
      '..KWWWWWWK..',
      '...KKKKKK...',
      '............',
    ],
    ddakji: [
      '............',
      '.KKKKKKKKKK.',
      '.KKBBBBBBKK.',
      '.KRKBBBBKRK.',
      '.KRRKBBKRRK.',
      '.KRRRKKRRRK.',
      '.KRRRKKRRRK.',
      '.KRRKBBKRRK.',
      '.KRKBBBBKRK.',
      '.KKBBBBBBKK.',
      '.KKKKKKKKKK.',
      '............',
    ],
    marble: [
      '............',
      '....KKKK....',
      '..KKUUUUKK..',
      '..KUHHUNNK..',
      '.KUHUUNNUUK.',
      '.KUUUNNUUUK.',
      '.KUUNNUUUUK.',
      '.KUNNUUUUbK.',
      '..KUUUUUbK..',
      '..KKbbbbKK..',
      '....KKKK....',
      '............',
    ],
    deadbattery: [
      '............',
      '.....KK.....',
      '....KggK....',
      '...KKKKKK...',
      '...KEEEEK...',
      '...KEEEEK...',
      '...KDDDDK...',
      '...KDHDDK...',
      '...KDDDDK...',
      '...KDDDDK...',
      '...KKKKKK...',
      '............',
    ],
    oldkey: [
      '............',
      '............',
      '..KKKK......',
      '.KyEEyK.....',
      '.KEKKEKKKKKK',
      '.KEK.KEEEEEK',
      '.KEKKEKKEKEK',
      '.KyEEyK.KyKy',
      '..KKKK...K.K',
      '............',
      '............',
      '............',
    ],
    bottlecap: [
      '............',
      '............',
      '............',
      '...KKKKKK...',
      '..KRRRRRRK..',
      '.KRHRRRRRrK.',
      '.KRRRRRRRrK.',
      '.KrRrRrRrrK.',
      '..KKKKKKKK..',
      '............',
      '............',
      '............',
    ],
    rubberband: [
      '............',
      '............',
      '...KKKKKK...',
      '..KYyyyyYK..',
      '.KYK....KYK.',
      '.KyK....KyK.',
      '.KYK....KYK.',
      '..KYyyyyYK..',
      '...KKKKKK...',
      '............',
      '............',
      '............',
    ],
    breadtie: [
      '............',
      '....KKKK....',
      '...KYyyYK...',
      '..KYK..KYK..',
      '..KyK..KyK..',
      '...KYKKYK...',
      '....KyYK....',
      '....KYyKK...',
      '...KYKKYYK..',
      '..KYK..KKyK.',
      '.KYK.....KK.',
      '.KK.........',
    ],
    receipt: [
      '............',
      '...KKKKKK...',
      '..KWWWWWWK..',
      '..KWGGGGWK..',
      '.KWWWWWWWK..',
      '.KWGGGWWWWK.',
      '..KWWWWWGWK.',
      '..KWGGGGWK..',
      '.KWWWWWWK...',
      '..KWGWGWK...',
      '...KKKKK....',
      '............',
    ],
    button: [
      '............',
      '............',
      '...KKKKKK...',
      '..KVVVVVVK..',
      '.KVVvVVvVVK.',
      '.KVVKVVKVVK.',
      '.KVVVVVVVVK.',
      '.KVVKVVKVVK.',
      '..KVVVVVVK..',
      '...KKKKKK...',
      '............',
      '............',
    ],
    dustball: [
      '............',
      '.....g......',
      '..g.KKKK.g..',
      '...KGGgGK...',
      '..KGgGGGgK..',
      '.gKGGGgGGKg.',
      '..KgGGGGgK..',
      '...KGgGGK...',
      '..g.KKKK.g..',
      '......g.....',
      '............',
      '............',
    ],
    toothpick: [
      '............',
      '..........K.',
      '.........KT.',
      '........KTK.',
      '.......KTK..',
      '......KTK...',
      '.....KTK....',
      '....KTK.....',
      '...KTK......',
      '..KTK.......',
      '..TK........',
      '............',
    ],
    clip: [
      '............',
      '..DD......D.',
      '.D..D....g..',
      '.g..D...D...',
      '.D..D..D....',
      '.D..g..D....',
      '.D..D..g....',
      '.D.....D....',
      '.D.....D....',
      '..D...D.....',
      '...DDD......',
      '............',
    ],
    dryleaf: [
      '............',
      '.........KK.',
      '.......KKOK.',
      '.....KKOOoK.',
      '....KOOOoOK.',
      '...KOOoOOK..',
      '..KOoOOOK...',
      '..KoOOOK....',
      '.KoOOKK.....',
      '.KKK........',
      'Kt..........',
      '............',
    ],
    pebble: [
      '............',
      '............',
      '............',
      '....KKKK....',
      '..KKGGGGKK..',
      '.KGGGHGGGgK.',
      '.KGGGGGGggK.',
      '.KgGGGGgggK.',
      '..KKggggKK..',
      '....KKKK....',
      '............',
      '............',
    ],
    crumb: [
      '............',
      '............',
      '............',
      '..KK........',
      '.KTTK...KK..',
      '.KTtK..KTTK.',
      '..KK...KtTK.',
      '.....K..KK..',
      '....KTK.....',
      '.....K..KK..',
      '.......KTK..',
      '........K...',
    ],
    candywrap: [
      '............',
      '............',
      '............',
      '.K........K.',
      '.KPK.KKK.KPK',
      '.KPPKPPPKPPK',
      '.KPQPPQPPQPK',
      '.KPPKPPPKPPK',
      '.KPK.KKK.KPK',
      '.K........K.',
      '............',
      '............',
    ],
    pigeonfeather: [
      '............',
      '.........KK.',
      '........KGK.',
      '.......KGgK.',
      '......KGgGK.',
      '.....KGgGK..',
      '....KGgGK...',
      '...KGgGK....',
      '..KGgKK.....',
      '..KgK.......',
      '.KD.........',
      'K...........',
    ],
    seedshell: [
      '............',
      '............',
      '....KKK.....',
      '...KXWXK....',
      '..KXWXWXK...',
      '..KXWXWXK...',
      '..KXWXWXK...',
      '...KXWXK....',
      '....KXK.....',
      '.....K......',
      '............',
      '............',
    ],
    twig: [
      '............',
      '..........K.',
      '.........KtK',
      '..K.....KtK.',
      '.KtK...KtK..',
      '..KtK.KtK...',
      '...KtKtK....',
      '....KttK....',
      '...KtK......',
      '..KtK.......',
      '.KtK........',
      '.KK.........',
    ],
    worm: [
      '............',
      '............',
      '............',
      '........KK..',
      '.......KpPK.',
      '..KK..KpPK..',
      '.KpPK.KpK...',
      '.KpPPKpPK...',
      '..KpPpPK....',
      '...KKKK.....',
      '............',
      '............',
    ],
    acorn: [
      '............',
      '.....K......',
      '....KtK.....',
      '..KKKKKKK...',
      '.KcCcCcCcK..',
      '.KCcCcCcCK..',
      '..KTTTTTK...',
      '..KTtTTTK...',
      '..KTTtTTK...',
      '...KTTTK....',
      '....KKK.....',
      '............',
    ],
    cicada: [
      '............',
      '..KKKKKKKK..',
      '.KcKTTTTKcK.',
      '..KTTSSTTK..',
      'KKKTTSSTtKKK',
      '..KTTSSTtK..',
      '.KKTtTTtTKK.',
      'K.KtTTTTtK.K',
      '...KTttTK...',
      '..KKTttTKK..',
      '.K..KTTK..K.',
      '.....KK.....',
    ],
    crayon: [
      '............',
      '............',
      '............',
      '..KKKKKKKK..',
      '.KRHRWWWWRK.',
      'KRRRRWrrWRRK',
      '.KrrrWWWWrK.',
      '..KKKKKKKK..',
      '............',
      '.......KKK..',
      '......KRRrK.',
      '.......KKK..',
    ],
    coin10: [
      '............',
      '...KKKKKK...',
      '..KSSTTTTK..',
      '.KSTTTTTTtK.',
      '.KTTCTCCCtK.',
      '.KTCCTCTCtK.',
      '.KTTCTCTCtK.',
      '.KTTCTCTCtK.',
      '.KTTCTCCCtK.',
      '.KtTTTTTTtK.',
      '..KttttttK..',
      '...KKKKKK...',
    ],
    keycap: [
      '............',
      '............',
      '.KKKKKKKKKK.',
      '.KWWWWWWWWK.',
      '.KWDDWDDWWK.',
      '.KWDWWDWWWK.',
      '.KWDDWDDWWK.',
      '.KWDWWWDWWK.',
      '.KWDDWDDWWK.',
      '.KGGGGGGGGK.',
      '.KKKKKKKKKK.',
      '............',
    ],
    eartip: [
      '............',
      '............',
      '............',
      '....KKKK....',
      '...KDDDDK...',
      '..KDgDDDDK..',
      '..KDDDDDDK..',
      '..KKKDDKKK..',
      '....KDDK....',
      '....KKKK....',
      '............',
      '............',
    ],
    lego: [
      '............',
      '............',
      '..KK..KK....',
      '.KRRK.KRRK..',
      'KKKKKKKKKK..',
      'KRHRRRRRRK..',
      'KRRRRRRRrK..',
      'KrrrrrrrrK..',
      'KKKKKKKKKK..',
      '............',
      '............',
      '............',
    ],
    postit: [
      '............',
      '.KKKKKKKKKK.',
      '.KYYYYYYYYK.',
      '.KYDDYDYYYK.',
      '.KYYYYYYYYK.',
      '.KYDYDDYDYK.',
      '.KYYYYYYYYK.',
      '.KYDDYYYYYK.',
      '.KYYYYYYyyK.',
      '.KKKKKKKyK..',
      '.........K..',
      '............',
    ],
    shinycap: [
      '.H..........',
      'HHH.......H.',
      '.H.KKKKKK...',
      '..KYYYYYYK..',
      '.KYHYYYYYyK.',
      '.KYYYYYYYyK.',
      '.KyYyYyYyyK.',
      '..KKKKKKKK..',
      '.........H..',
      '........HHH.',
      '.........H..',
      '............',
    ],
    clover3: [
      '............',
      '....KK......',
      '...KNNK.KK..',
      '...KNnNKNNK.',
      '....KNNNnNK.',
      '..KKKNNKKK..',
      '.KNNnNNK....',
      '.KNnNKNK....',
      '..KKK.KnK...',
      '.......KnK..',
      '........KK..',
      '............',
    ],
    lottery: [
      '............',
      'KKKKKKKKKKKK',
      'KWWWWWWWWWWK',
      'KWRWWRWRRWWK',
      'KWWWWWWWWWWK',
      'KWGGGGGGGGWK',
      'KWGRRGGRRGWK',
      'KWGGRRRRGGWK',
      'KWGGGGGGGGWK',
      'KKKKKKKKKKKK',
      '............',
      '............',
    ],
    usbcap: [
      '............',
      '............',
      '............',
      '............',
      '.KKKKKKKKKK.',
      '.KBHHBBBBbgK',
      '.KBBBBBBBbXK',
      '.KBBBBBBBbXK',
      '.KbbbbbbbbgK',
      '.KKKKKKKKKK.',
      '............',
      '............',
    ],
    bird1: [
      '..............',
      '...KK.....KK..',
      '...KGK...KGK..',
      '....KGK.KGK...',
      '.....KGKGK..K.',
      '..KKKGGGGKKKY.',
      '.KDGGGGGGGKK..',
      'KKDgGGGGGK....',
      '...KKKKKKK....',
      '....K...K.....',
    ],
    bird2: [
      '..............',
      '..............',
      '..............',
      '..........KK..',
      '..KKKKKKKKGKY.',
      '.KDGGGGGGGKK..',
      'KKDgGGGGGK....',
      '...KGKKKGK....',
      '....KGK.KGK...',
      '.....K...K....',
    ],
  };

  // 이름 → [도트, 팔레트]. 먹이가 먼저다
  const find = (name) => (FOOD[name] ? [FOOD[name], FOOD_PALETTE] : TOY[name] ? [TOY[name], FOOD_PALETTE] : TREASURE[name] ? [TREASURE[name], FOOD_PALETTE] : ICONS[name] ? [ICONS[name], PALETTE] : [null, PALETTE]);
  const has = (name) => !!find(name)[0];
  const size = (name) => {
    const [rows] = find(name);
    return rows ? { w: rows[0].length, h: rows.length } : null;
  };

  // 같은 색이 가로로 이어지면 사각형 하나로 묶는다. 아이콘 하나가 길어야 스무 줄 남짓이다
  // frame 을 주면 움직이는 먹이(FOOD_ANIM)의 그 프레임을 그린다 (house.js 가 상점 카드에서 돌린다)
  function svg(name, px = 16, cls = '', frame) {
    const [found, PALETTE] = find(name);
    const rows = frame != null && FOOD_ANIM[name] ? frameRows(name, frame) : found;
    if (!rows) return '';
    const w = rows[0].length;
    const h = rows.length;
    let body = '';
    for (let y = 0; y < h; y++) {
      let x = 0;
      while (x < w) {
        const ch = rows[y][x];
        if (!PALETTE[ch]) {
          x++;
          continue;
        }
        let n = 1;
        while (x + n < w && rows[y][x + n] === ch) n++;
        body += `<rect x="${x}" y="${y}" width="${n}" height="1" fill="${PALETTE[ch]}"/>`;
        x += n;
      }
    }
    // 긴 쪽을 px 에 맞추고 짧은 쪽은 비율대로 줄인다
    const ww = w >= h ? px : Math.round((px * w) / h);
    const hh = h >= w ? px : Math.round((px * h) / w);
    return `<svg class="pxi${cls ? ' ' + cls : ''}" width="${ww}" height="${hh}" viewBox="0 0 ${w} ${h}" shape-rendering="crispEdges" aria-hidden="true">${body}</svg>`;
  }

  // 캔버스에 통째로 찍는다. scale 은 도트 한 칸의 화면 크기 (장난감이 쓴다)
  function paint(canvas, name, scale = 3) {
    const [rows, PALETTE] = find(name);
    if (!rows) return false;
    const w = rows[0].length;
    const h = rows.length;
    canvas.width = w;
    canvas.height = h;
    canvas.style.width = `${w * scale}px`;
    canvas.style.height = `${h * scale}px`;
    const ctx = canvas.getContext('2d');
    ctx.clearRect(0, 0, w, h);
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const c = PALETTE[rows[y][x]];
        if (!c) continue;
        ctx.fillStyle = c;
        ctx.fillRect(x, y, 1, 1);
      }
    }
    return true;
  }

  // 메인 프로세스용. px×px RGBA(또는 BGRA) 버퍼를 만든다.
  // 배율은 정수로만 키워서 도트가 뭉개지지 않게 한다
  const hex = (s) => [parseInt(s.slice(1, 3), 16), parseInt(s.slice(3, 5), 16), parseInt(s.slice(5, 7), 16)];
  const toRgb = (pal) => Object.fromEntries(Object.entries(pal).map(([ch, v]) => [ch, hex(v)]));
  const RGB_BASE = toRgb(PALETTE);
  const FOOD_RGB = toRgb(FOOD_PALETTE);

  function rgba(name, px = 16, bgra = false) {
    const buf = Buffer.alloc(px * px * 4);
    const rows = FOOD[name] || TOY[name] || TREASURE[name] || ICONS[name];
    const RGB = FOOD[name] || TOY[name] || TREASURE[name] ? FOOD_RGB : RGB_BASE;
    if (!rows) return buf;
    const w = rows[0].length;
    const h = rows.length;
    const k = Math.max(1, Math.floor(px / Math.max(w, h)));
    const ox = Math.floor((px - w * k) / 2);
    const oy = Math.floor((px - h * k) / 2);
    for (let y = 0; y < h * k; y++) {
      for (let x = 0; x < w * k; x++) {
        const c = RGB[rows[(y / k) | 0][(x / k) | 0]];
        if (!c) continue;
        const dx = x + ox;
        const dy = y + oy;
        if (dx < 0 || dy < 0 || dx >= px || dy >= px) continue;
        const i = (dy * px + dx) * 4;
        buf[i] = bgra ? c[2] : c[0];
        buf[i + 1] = c[1];
        buf[i + 2] = bgra ? c[0] : c[2];
        buf[i + 3] = 255;
      }
    }
    return buf;
  }

  return { PALETTE, ICONS, FOOD_PALETTE, FOOD, FOOD_ANIM, TOY, TREASURE, has, size, svg, paint, rgba, frameRows };
});
